### ISSUE TITLE
fbs install fails on macOS with hdiutil resize failed error

### ISSUE THREAD

**Issue by j9ac9k** [mherrmann/fbs#105]
fbs version: 0.7.7 
macOS: 10.14
python: 3.7
qt-bindings: pyside2 5.12.2

I'm attempting to run `fbs installer` on macOS, and I get the following error:

```
Loading .env environment variables…
hdiutil: resize request 268288 is below minimum size 430592 allowed.
hdiutil: resize: failed. Invalid argument (22)
Traceback (most recent call last):
  File "/Users/ognyan/Developer/fred/.venv/bin/fbs", line 10, in <module>
    sys.exit(_main())
  File "/Users/ognyan/Developer/fred/.venv/lib/python3.7/site-packages/fbs/__main__.py", line 17, in _main
    fbs.cmdline.main()
  File "/Users/ognyan/Developer/fred/.venv/lib/python3.7/site-packages/fbs/cmdline.py", line 32, in main
    fn(*args)
  File "/Users/ognyan/Developer/fred/.venv/lib/python3.7/site-packages/fbs/builtin_commands/__init__.py", line 163, in installer
    create_installer_mac()
  File "/Users/ognyan/Developer/fred/.venv/lib/python3.7/site-packages/fbs/installer/mac/__init__.py", line 21, in create_installer_mac
    ], stdout=DEVNULL)
  File "/Users/ognyan/.pyenv/versions/miniconda3-latest/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/ognyan/Developer/fred/.venv/lib/python3.7/site-packages/fbs/installer/mac/create-dmg/create-dmg', '--volname', 'Fred', '--app-drop-link', '170', '10', '--icon', 'Fred.app', '0', '10', '/Users/ognyan/Developer/fred/target/Fred.dmg', '/Users/ognyan/Developer/fred/target/Fred.app']' returned non-zero exit status 22.
```

I downgraded to 0.7.4, and got the same error.

Suggestions as to steps to try and troubleshoot?

**Comment by j9ac9k** [comment]
I did some more debugging, and I'm starting to suspect this may be an macOS 10.14.4 issue (vs. 10.14.3).  I get the same error even when I recreate a project using `fbs startproject` with python 3.7 or python 3.6.

```
$ fbs startproject # finishes w/o error
$ fbs freeze . # finishes w/o error
$ fbs installer 

hdiutil: resize request 116736 is below minimum size 140944 allowed.
hdiutil: resize: failed. Invalid argument (22)
Traceback (most recent call last):
  File "/Users/ognyan/.pyenv/versions/fbs-test-36/bin/fbs", line 11, in <module>
    load_entry_point('fbs==0.7.8', 'console_scripts', 'fbs')()
  File "/Users/ognyan/.pyenv/versions/3.6.8/envs/fbs-test-36/lib/python3.6/site-packages/fbs/__main__.py", line 17, in _main
    fbs.cmdline.main()
  File "/Users/ognyan/.pyenv/versions/3.6.8/envs/fbs-test-36/lib/python3.6/site-packages/fbs/cmdline.py", line 32, in main
    fn(*args)
  File "/Users/ognyan/.pyenv/versions/3.6.8/envs/fbs-test-36/lib/python3.6/site-packages/fbs/builtin_commands/__init__.py", line 160, in installer
    create_installer_mac()
  File "/Users/ognyan/.pyenv/versions/3.6.8/envs/fbs-test-36/lib/python3.6/site-packages/fbs/installer/mac/__init__.py", line 21, in create_installer_mac
    ], stdout=DEVNULL)
  File "/Users/ognyan/.pyenv/versions/3.6.8/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/ognyan/.pyenv/versions/3.6.8/envs/fbs-test-36/lib/python3.6/site-packages/fbs/installer/mac/create-dmg/create-dmg', '--volname', 'Fred', '--app-drop-link', '170', '10', '--icon', 'Fred.app', '0', '10', '/Users/ognyan/Developer/fbs-test/target/Fred.dmg', '/Users/ognyan/Developer/fbs-test/target/Fred.app']' returned non-zero exit status 22.
```

I have the same issue with both PyQt5 and PySide2

**Comment by j9ac9k** [comment]
got the DMG to build successfully on my "test" user account; so there is some environmental factor in play.

**Comment by j9ac9k** [comment]
I isolated the cause; going to document it here in case anyone has the same issue.  The problem was having homebrew coreutils package added to my PATH caused a conflict

```sh
export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
```

Commenting out that line in my `.zshrc` completely resolved my issue.  I am puzzled as to why this became a problem now and fbs was behaving fine earlier, that I anticipate had to do with my upgrade to Mojave 10.14.4 (from 10.14.3) but who knows.

**Comment by mherrmann** [comment]
Happy to hear it works now. Thanks for sharing your solution!
