### ISSUE TITLE
shiboken2.support ImportError during fbs freeze on pyside2 5.12.3 (works on 5.12.2)

### ISSUE THREAD

**Issue by j9ac9k** [mherrmann/fbs#109]
Environment Information

* Windows 10 Pro x64 and macOS 10.14.4
* Python 3.7.3-amd64 (windows) and Python 3.6.8/3.7.3 (macOS) 
* fbs version 0.7.9
* pyinstaller 3.4
* pyside2 5.12.3

```
$ fbs freeze
Traceback (most recent call last):
  File "C:\Users\ogi\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\ogi\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\ogi\Developer\fbs-test\.venv\Scripts\pyinstaller.exe\__main__.py", line 9, in <module>
  File "c:\users\ogi\developer\fbs-test\.venv\lib\site-packages\PyInstaller\__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\users\ogi\developer\fbs-test\.venv\lib\site-packages\PyInstaller\__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\users\ogi\developer\fbs-test\.venv\lib\site-packages\PyInstaller\building\build_main.py", line 838, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\users\ogi\developer\fbs-test\.venv\lib\site-packages\PyInstaller\building\build_main.py", line 784, in build
    exec(text, spec_namespace)
  File "<string>", line 17, in <module>
  File "c:\users\ogi\developer\fbs-test\.venv\lib\site-packages\PyInstaller\building\build_main.py", line 241, in __init__
    self.__postinit__()
  File "c:\users\ogi\developer\fbs-test\.venv\lib\site-packages\PyInstaller\building\datastruct.py", line 158, in __postinit__
    self.assemble()
  File "c:\users\ogi\developer\fbs-test\.venv\lib\site-packages\PyInstaller\building\build_main.py", line 500, in assemble
    module_hook.post_graph()
  File "c:\users\ogi\developer\fbs-test\.venv\lib\site-packages\PyInstaller\building\imphook.py", line 410, in post_graph
    self._load_hook_module()
  File "c:\users\ogi\developer\fbs-test\.venv\lib\site-packages\PyInstaller\building\imphook.py", line 377, in _load_hook_module
    self.hook_module_name, self.hook_filename)
  File "c:\users\ogi\developer\fbs-test\.venv\lib\site-packages\PyInstaller\compat.py", line 736, in importlib_load_source
    return mod_loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 407, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 907, in load_module
  File "<frozen importlib._bootstrap_external>", line 732, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "c:\users\ogi\developer\fbs-test\.venv\lib\site-packages\fbs\freeze\hooks\hook-shiboken2.py", line 9, in <module>
    import shiboken2.support as support
ModuleNotFoundError: No module named 'shiboken2.support'
Traceback (most recent call last):
  File "C:\Users\ogi\Developer\fbs-test\.venv\Scripts\fbs-script.py", line 11, in <module>
    load_entry_point('fbs==0.7.9', 'console_scripts', 'fbs')()
  File "c:\users\ogi\developer\fbs-test\.venv\lib\site-packages\fbs\__main__.py", line 17, in _main
    fbs.cmdline.main()
  File "c:\users\ogi\developer\fbs-test\.venv\lib\site-packages\fbs\cmdline.py", line 32, in main
    fn(*args)
  File "c:\users\ogi\developer\fbs-test\.venv\lib\site-packages\fbs\builtin_commands\__init__.py", line 120, in freeze
    freeze_windows(debug=debug)
  File "c:\users\ogi\developer\fbs-test\.venv\lib\site-packages\fbs\freeze\windows.py", line 18, in freeze_windows
    run_pyinstaller(args, debug)
  File "c:\users\ogi\developer\fbs-test\.venv\lib\site-packages\fbs\freeze\__init__.py", line 48, in run_pyinstaller
    run(args, check=True)
  File "C:\Users\ogi\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['pyinstaller', '--name', 'MyApp', '--noupx', '--log-level', 'ERROR', '--noconfirm', '--windowed', '--icon', 'C:\\Users\\ogi\\Developer\\fbs-test\\src\\main\\icons\\Icon.ico', '--distpath', 'C:\\Users\\ogi\\Developer\\fbs-test\\target', '--specpath', 'C:\\Users\\ogi\\Developer\\fbs-test\\target\\PyInstaller', '--workpath', 'C:\\Users\\ogi\\Developer\\fbs-test\\target\\PyInstaller', '--additional-hooks-dir', 'c:\\users\\ogi\\developer\\fbs-test\\.venv\\lib\\site-packages\\fbs\\freeze\\hooks', '--runtime-hook', 'C:\\Users\\ogi\\AppData\\Local\\Temp\\tmpjodcyfe4\\fbs_pyinstaller_hook.py', 'C:\\Users\\ogi\\Developer\\fbs-test\\src\\main\\python\\main.py']' returned non-zero exit status 1.
```

Reproduction steps

```
pip install pyside2  # this installs pyside2 5.12.3
pip install fbs
fbs startproject
fbs run  # this works
fbs freeze  # import error with shiboken2.support
```

Per the troubleshooting steps, I added `shiboken2.support` to the list of `hidden_imports` in `base.json`; but still have the identical issue.

<details>
  <summary>fbs freeze --debug output</summary>
  
```
$ fbs freeze --debug
75 INFO: PyInstaller: 3.4
75 INFO: Python: 3.7.3
75 INFO: Platform: Windows-10-10.0.17763-SP0
75 INFO: wrote C:\Users\ogi\Developer\fbs-test\target\PyInstaller\MyApp.spec
75 DEBUG: Testing for UPX ...
75 INFO: UPX is not available.
75 DEBUG: script: C:\Users\ogi\Developer\fbs-test\src\main\python\main.py
75 INFO: Extending PYTHONPATH with paths
['C:\\Users\\ogi\\Developer\\fbs-test\\src\\main\\python',
 'C:\\Users\\ogi\\Developer\\fbs-test\\target\\PyInstaller']
75 INFO: checking Analysis
75 INFO: Building Analysis because Analysis-00.toc is non existent
75 INFO: Initializing module dependency graph...
75 INFO: Initializing module graph hooks...
91 INFO: Analyzing base_library.zip ...
91 DEBUG: Collecting submodules for encodings
185 DEBUG: collect_submodules - Found submodules: {'encodings.mbcs', 'encodings.cp864', 'encodings.hex_codec', 'encodings.mac_latin2', 'encodings.euc_jp', 'encodings.iso2022_jp_1', 'encodings.cp1256', 'encodings.oem', 'encodings.cp866', 'encodings.mac_farsi', 'encodings.cp1125', 'encodings.cp500', 'encodings.koi8_r', 'encodings.ascii', 'encodings.raw_unicode_escape', 'encodings.punycode', 'encodings.cp860', 'encodings.iso8859_1', 'encodings.cp874', 'encodings.cp775', 'encodings.cp1140', 'encodings.utf_16_le', 'encodings.mac_greek', 'encodings.utf_32', 'encodings.shift_jis', 'encodings.cp1252', 'encodings.euc_jis_2004', 'encodings.iso8859_10', 'encodings.cp037', 'encodings.cp1026', 'encodings.hp_roman8', 'encodings.iso8859_6', 'encodings.cp1258', 'encodings.cp863', 'encodings.iso2022_jp_3', 'encodings.cp950', 'encodings.hz', 'encodings.iso8859_14', 'encodings.iso8859_9', 'encodings.shift_jisx0213', 'encodings.cp273', 'encodings.quopri_codec', 'encodings.cp1251', 'encodings.mac_arabic', 'encodings.mac_croatian', 'encodings.iso2022_jp_2004', 'encodings.idna', 'encodings.iso2022_jp_2', 'encodings.gbk', 'encodings.mac_turkish', 'encodings.tis_620', 'encodings.iso8859_7', 'encodings.utf_8_sig', 'encodings.iso2022_jp', 'encodings.utf_32_be', 'encodings.mac_centeuro', 'encodings.johab', 'encodings.uu_codec', 'encodings.cp932', 'encodings.aliases', 'encodings.unicode_escape', 'encodings.iso8859_15', 'encodings.utf_16', 'encodings.cp1006', 'encodings.shift_jis_2004', 'encodings.cp1255', 'encodings.charmap', 'encodings.cp720', 'encodings.big5hkscs', 'encodings.iso8859_13', 'encodings.cp65001', 'encodings.kz1048', 'encodings.cp850', 'encodings.iso8859_8', 'encodings.cp949', 'encodings.cp857', 'encodings.rot_13', 'encodings.cp862', 'encodings.latin_1', 'encodings.utf_16_be', 'encodings.iso8859_3', 'encodings.mac_cyrillic', 'encodings.iso8859_2', 'encodings.gb2312', 'encodings.koi8_u', 'encodings.mac_roman', 'encodings.euc_kr', 'encodings.utf_32_le', 'encodings.ptcp154', 'encodings.cp1254', 'encodings.gb18030', 'encodings.koi8_t', 'encodings.cp424', 'encodings.cp852', 'encodings.cp869', 'encodings', 'encodings.iso2022_jp_ext', 'encodings.cp865', 'encodings.cp1250', 'encodings.cp855', 'encodings.cp737', 'encodings.cp858', 'encodings.iso8859_16', 'encodings.cp856', 'encodings.undefined', 'encodings.iso8859_5', 'encodings.iso8859_4', 'encodings.mac_romanian', 'encodings.cp875', 'encodings.euc_jisx0213', 'encodings.cp1253', 'encodings.utf_7', 'encodings.cp437', 'encodings.unicode_internal', 'encodings.iso8859_11', 'encodings.utf_8', 'encodings.big5', 'encodings.palmos', 'encodings.base64_codec', 'encodings.mac_iceland', 'encodings.cp861', 'encodings.zlib_codec', 'encodings.cp1257', 'encodings.bz2_codec', 'encodings.iso2022_kr'}
185 DEBUG: Collecting submodules for collections
310 DEBUG: collect_submodules - Found submodules: {'collections.abc', 'collections'}
3808 DEBUG: Adding python files to base_library.zip
3856 DEBUG: Hidden import: shiboken2.support
3856 INFO: Analyzing hidden import 'shiboken2.support'
3871 ERROR: Hidden import 'shiboken2.support' not found
3871 DEBUG: Hidden import: codecs
3871 DEBUG: Hidden import 'codecs' already found
3871 INFO: running Analysis Analysis-00.toc
3871 DEBUG: Analyzing c:\users\ogi\developer\fbs-test\.venv\scripts\python.exe
3886 DEBUG: Dependent assemblies of c:\users\ogi\developer\fbs-test\.venv\scripts\python.exe:
3886 DEBUG: *_Microsoft.Windows.Common-Controls_6595b64144ccf1df_6.0.0.0_none
3886 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by c:\users\ogi\developer\fbs-test\.venv\scripts\python.exe
3886 DEBUG: Skipping assembly *_Microsoft.Windows.Common-Controls_6595b64144ccf1df_6.0.0.0_none
3886 DEBUG: Skipping VERSION.dll dependency of python.exe
3902 DEBUG: Skipping ADVAPI32.dll dependency of python.exe
3902 DEBUG: Skipping KERNEL32.dll dependency of python.exe
3902 INFO: Caching module hooks...
3918 INFO: Analyzing C:\Users\ogi\Developer\fbs-test\src\main\python\main.py
4091 INFO: Loading module hooks...
4091 INFO: Loading module hook "hook-encodings.py"...
4091 DEBUG: Collecting submodules for encodings
4184 DEBUG: collect_submodules - Found submodules: {'encodings.mbcs', 'encodings.cp864', 'encodings.hex_codec', 'encodings.mac_latin2', 'encodings.euc_jp', 'encodings.iso2022_jp_1', 'encodings.cp1256', 'encodings.oem', 'encodings.cp866', 'encodings.mac_farsi', 'encodings.cp1125', 'encodings.cp500', 'encodings.koi8_r', 'encodings.ascii', 'encodings.raw_unicode_escape', 'encodings.punycode', 'encodings.cp860', 'encodings.iso8859_1', 'encodings.cp874', 'encodings.cp775', 'encodings.cp1140', 'encodings.utf_16_le', 'encodings.mac_greek', 'encodings.utf_32', 'encodings.shift_jis', 'encodings.cp1252', 'encodings.euc_jis_2004', 'encodings.iso8859_10', 'encodings.cp037', 'encodings.cp1026', 'encodings.hp_roman8', 'encodings.iso8859_6', 'encodings.cp1258', 'encodings.cp863', 'encodings.iso2022_jp_3', 'encodings.cp950', 'encodings.hz', 'encodings.iso8859_14', 'encodings.iso8859_9', 'encodings.shift_jisx0213', 'encodings.cp273', 'encodings.quopri_codec', 'encodings.cp1251', 'encodings.mac_arabic', 'encodings.mac_croatian', 'encodings.iso2022_jp_2004', 'encodings.idna', 'encodings.iso2022_jp_2', 'encodings.gbk', 'encodings.mac_turkish', 'encodings.tis_620', 'encodings.iso8859_7', 'encodings.utf_8_sig', 'encodings.iso2022_jp', 'encodings.utf_32_be', 'encodings.mac_centeuro', 'encodings.johab', 'encodings.uu_codec', 'encodings.cp932', 'encodings.aliases', 'encodings.unicode_escape', 'encodings.iso8859_15', 'encodings.utf_16', 'encodings.cp1006', 'encodings.shift_jis_2004', 'encodings.cp1255', 'encodings.charmap', 'encodings.cp720', 'encodings.big5hkscs', 'encodings.iso8859_13', 'encodings.cp65001', 'encodings.kz1048', 'encodings.cp850', 'encodings.iso8859_8', 'encodings.cp949', 'encodings.cp857', 'encodings.rot_13', 'encodings.cp862', 'encodings.latin_1', 'encodings.utf_16_be', 'encodings.iso8859_3', 'encodings.mac_cyrillic', 'encodings.iso8859_2', 'encodings.gb2312', 'encodings.koi8_u', 'encodings.mac_roman', 'encodings.euc_kr', 'encodings.utf_32_le', 'encodings.ptcp154', 'encodings.cp1254', 'encodings.gb18030', 'encodings.koi8_t', 'encodings.cp424', 'encodings.cp852', 'encodings.cp869', 'encodings', 'encodings.iso2022_jp_ext', 'encodings.cp865', 'encodings.cp1250', 'encodings.cp855', 'encodings.cp737', 'encodings.cp858', 'encodings.iso8859_16', 'encodings.cp856', 'encodings.undefined', 'encodings.iso8859_5', 'encodings.iso8859_4', 'encodings.mac_romanian', 'encodings.cp875', 'encodings.euc_jisx0213', 'encodings.cp1253', 'encodings.utf_7', 'encodings.cp437', 'encodings.unicode_internal', 'encodings.iso8859_11', 'encodings.utf_8', 'encodings.big5', 'encodings.palmos', 'encodings.base64_codec', 'encodings.mac_iceland', 'encodings.cp861', 'encodings.zlib_codec', 'encodings.cp1257', 'encodings.bz2_codec', 'encodings.iso2022_kr'}
4184 INFO: Loading module hook "hook-pydoc.py"...
4184 INFO: Loading module hook "hook-PySide2.py"...
4184 DEBUG: Collecting data files for PySide2
4184 DEBUG: collect_data_files - Found files: []
4184 WARNING: Hidden import "numpy.core.multiarray" not found!
4184 INFO: Loading module hook "hook-PySide2.py"...
4200 WARNING: Hidden import "numpy.core.multiarray" not found!
4200 INFO: Loading module hook "hook-PySide2.QtGui.py"...
4385 DEBUG: Found plugin files [] for plugin 'accessible
4551 DEBUG: Found plugin files ['C:/users/ogi/developer/fbs-test/.venv/lib/site-packages/PySide2/plugins\\iconengines\\qsvgicon.dll'] for plugin 'iconengines
4701 DEBUG: Found plugin files ['C:/users/ogi/developer/fbs-test/.venv/lib/site-packages/PySide2/plugins\\imageformats\\qgif.dll', 'C:/users/ogi/developer/fbs-test/.venv/lib/site-packages/PySide2/plugins\\imageformats\\qicns.dll', 'C:/users/ogi/developer/fbs-test/.venv/lib/site-packages/PySide2/plugins\\imageformats\\qico.dll', 'C:/users/ogi/developer/fbs-test/.venv/lib/site-packages/PySide2/plugins\\imageformats\\qjpeg.dll', 'C:/users/ogi/developer/fbs-test/.venv/lib/site-packages/PySide2/plugins\\imageformats\\qsvg.dll', 'C:/users/ogi/developer/fbs-test/.venv/lib/site-packages/PySide2/plugins\\imageformats\\qtga.dll', 'C:/users/ogi/developer/fbs-test/.venv/lib/site-packages/PySide2/plugins\\imageformats\\qtiff.dll', 'C:/users/ogi/developer/fbs-test/.venv/lib/site-packages/PySide2/plugins\\imageformats\\qwbmp.dll', 'C:/users/ogi/developer/fbs-test/.venv/lib/site-packages/PySide2/plugins\\imageformats\\qwebp.dll'] for plugin 'imageformats
4867 DEBUG: Found plugin files [] for plugin 'inputmethods
5038 DEBUG: Found plugin files [] for plugin 'graphicssystems
5219 DEBUG: Found plugin files ['C:/users/ogi/developer/fbs-test/.venv/lib/site-packages/PySide2/plugins\\platforms\\qminimal.dll', 'C:/users/ogi/developer/fbs-test/.venv/lib/site-packages/PySide2/plugins\\platforms\\qoffscreen.dll', 'C:/users/ogi/developer/fbs-test/.venv/lib/site-packages/PySide2/plugins\\platforms\\qwebgl.dll', 'C:/users/ogi/developer/fbs-test/.venv/lib/site-packages/PySide2/plugins\\platforms\\qwindows.dll'] for plugin 'platforms
5392 DEBUG: Found plugin files ['C:/users/ogi/developer/fbs-test/.venv/lib/site-packages/PySide2/plugins\\styles\\qwindowsvistastyle.dll'] for plugin 'styles
5394 INFO: Loading module hook "hook-PySide2.QtNetwork.py"...
5588 DEBUG: Found plugin files ['C:/users/ogi/developer/fbs-test/.venv/lib/site-packages/PySide2/plugins\\bearer\\qgenericbearer.dll'] for plugin 'bearer
5588 INFO: Loading module hook "hook-PySide2.QtWidgets.py"...
5588 INFO: Loading module hook "hook-xml.py"...
5864 INFO: Loading module hook "hook-shiboken2.py"...
Traceback (most recent call last):
  File "C:\Users\ogi\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\ogi\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\ogi\Developer\fbs-test\.venv\Scripts\pyinstaller.exe\__main__.py", line 9, in <module>
  File "c:\users\ogi\developer\fbs-test\.venv\lib\site-packages\PyInstaller\__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\users\ogi\developer\fbs-test\.venv\lib\site-packages\PyInstaller\__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\users\ogi\developer\fbs-test\.venv\lib\site-packages\PyInstaller\building\build_main.py", line 838, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\users\ogi\developer\fbs-test\.venv\lib\site-packages\PyInstaller\building\build_main.py", line 784, in build
    exec(text, spec_namespace)
  File "<string>", line 17, in <module>
  File "c:\users\ogi\developer\fbs-test\.venv\lib\site-packages\PyInstaller\building\build_main.py", line 241, in __init__
    self.__postinit__()
  File "c:\users\ogi\developer\fbs-test\.venv\lib\site-packages\PyInstaller\building\datastruct.py", line 158, in __postinit__
    self.assemble()
  File "c:\users\ogi\developer\fbs-test\.venv\lib\site-packages\PyInstaller\building\build_main.py", line 500, in assemble
    module_hook.post_graph()
  File "c:\users\ogi\developer\fbs-test\.venv\lib\site-packages\PyInstaller\building\imphook.py", line 410, in post_graph
    self._load_hook_module()
  File "c:\users\ogi\developer\fbs-test\.venv\lib\site-packages\PyInstaller\building\imphook.py", line 377, in _load_hook_module
    self.hook_module_name, self.hook_filename)
  File "c:\users\ogi\developer\fbs-test\.venv\lib\site-packages\PyInstaller\compat.py", line 736, in importlib_load_source
    return mod_loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 407, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 907, in load_module
  File "<frozen importlib._bootstrap_external>", line 732, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "c:\users\ogi\developer\fbs-test\.venv\lib\site-packages\fbs\freeze\hooks\hook-shiboken2.py", line 9, in <module>
    import shiboken2.support as support
ModuleNotFoundError: No module named 'shiboken2.support'
Traceback (most recent call last):
  File "C:\Users\ogi\Developer\fbs-test\.venv\Scripts\fbs-script.py", line 11, in <module>
    load_entry_point('fbs==0.7.9', 'console_scripts', 'fbs')()
  File "c:\users\ogi\developer\fbs-test\.venv\lib\site-packages\fbs\__main__.py", line 17, in _main
    fbs.cmdline.main()
  File "c:\users\ogi\developer\fbs-test\.venv\lib\site-packages\fbs\cmdline.py", line 32, in main
    fn(*args)
  File "c:\users\ogi\developer\fbs-test\.venv\lib\site-packages\fbs\builtin_commands\__init__.py", line 120, in freeze
    freeze_windows(debug=debug)
  File "c:\users\ogi\developer\fbs-test\.venv\lib\site-packages\fbs\freeze\windows.py", line 18, in freeze_windows
    run_pyinstaller(args, debug)
  File "c:\users\ogi\developer\fbs-test\.venv\lib\site-packages\fbs\freeze\__init__.py", line 48, in run_pyinstaller
    run(args, check=True)
  File "C:\Users\ogi\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['pyinstaller', '--name', 'MyApp', '--noupx', '--log-level', 'DEBUG', '--noconfirm', '--hidden-import', 'shiboken2.support', '--icon', 'C:\\Users\\ogi\\Developer\\fbs-test\\src\\main\\icons\\Icon.ico', '--distpath', 'C:\\Users\\ogi\\Developer\\fbs-test\\target', '--specpath', 'C:\\Users\\ogi\\Developer\\fbs-test\\target\\PyInstaller', '--workpath', 'C:\\Users\\ogi\\Developer\\fbs-test\\target\\PyInstaller', '--additional-hooks-dir', 'c:\\users\\ogi\\developer\\fbs-test\\.venv\\lib\\site-packages\\fbs\\freeze\\hooks', '--debug', 'all', '--runtime-hook', 'C:\\Users\\ogi\\AppData\\Local\\Temp\\tmp6seyuo5r\\fbs_pyinstaller_hook.py', 'C:\\Users\\ogi\\Developer\\fbs-test\\src\\main\\python\\main.py']' returned non-zero exit status 1.
```
</details>

Let me know if I can provide any other information.

**Comment by mherrmann** [comment]
Thanks! I just released version 0.8.0 that fixes this.

The `<details>` tag you used in the issue description is nifty :+1:

**Comment by j9ac9k** [comment]
Thanks for the fast turnaround!  Also thanks for providing `fbs startproject`; makes it much easier to submit a minimum working example.

**Comment by mherrmann** [comment]
Happy you are finding it useful :-)
