### ISSUE TITLE
fbs run gives KeyError: 'version' from  _source.load_build_settings

### ISSUE THREAD

**Issue by fredrikaverpil** [mherrmann/fbs#118]
Hi!

I just upgraded fbs from 0.5.0 to the current 0.8.2 and immediately got an error:

```python
Traceback (most recent call last):
  File "C:\Users\fredrik\code\repos\skalman\src\main\python\skalman\skalui\mainfbs.py", line 49, in <module>
    APP_CONTEXT = AppContext()
  File "c:\users\fredrik\code\repos\skalman\venv\lib\site-packages\fbs_runtime\application_context.py", line 39, in __init__
    self.app
  File "c:\users\fredrik\code\repos\skalman\venv\lib\site-packages\fbs_runtime\application_context.py", line 61, in app
    result.setApplicationName(self.build_settings['app_name'])
  File "c:\users\fredrik\code\repos\skalman\venv\lib\site-packages\fbs_runtime\application_context.py", line 72, in build_settings
    return _source.load_build_settings(self._project_dir)
  File "c:\users\fredrik\code\repos\skalman\venv\lib\site-packages\fbs_runtime\_source.py", line 38, in load_build_settings
    return filter_public_settings(all_settings)
  File "c:\users\fredrik\code\repos\skalman\venv\lib\site-packages\fbs_runtime\_fbs.py", line 27, in filter_public_settings
    return {k: settings[k] for k in settings['public_settings']}
  File "c:\users\fredrik\code\repos\skalman\venv\lib\site-packages\fbs_runtime\_fbs.py", line 27, in <dictcomp>
    return {k: settings[k] for k in settings['public_settings']}
KeyError: 'version'
```

I browsed the changelog (release notes) to figure out what was changed and what would cause this. It turns out that [fbs 0.7.5](https://github.com/mherrmann/fbs/releases/tag/v0.7.5) introduced this new behavior which caused this crash on my end.

If I add e.g. `"version": "0.0.0"` to my `src/build/settings/base.json`, I no longer get a crash and I can upgrade to the latest fbs 0.8.2.

However, I am already setting the version number to my window(s) by other means and I do not wish to specify the version in two places.

Can we please make this key optional?

**Comment by mherrmann** [comment]
I'm sorry I can't make this optional as it's used in many places and a pretty important setting for fbs apps. If you want to make it optional, just add the `"version": "0.0.0"` to `base.json` like you said. That has the same effect as me making it optional in fbs, for all fbs users.

**Comment by fredrikaverpil** [comment]
Ok, sounds good. Thanks!
