### ISSUE TITLE
Cannot execute program after freeze (matplotlib issue)

### ISSUE THREAD

**Issue by wjhuisman** [mherrmann/fbs#121]
Hi,

When I'm trying to execute my program after a (successful) freeze, I get the following error:

```Traceback (most recent call last):
  File "matplotlib/font_manager.py", line 1356, in <module>
  File "matplotlib/font_manager.py", line 891, in json_load
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp_i3yvqlt/fontlist-v300.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/main/python/main.py", line 4, in <module>
    from GUI import ui_main
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/home/wouter/Environments/StratosIV/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "GUI/ui_main.py", line 8, in <module>
    import GUI.RunCase.ui_run_case as test
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/home/wouter/Environments/StratosIV/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "GUI/RunCase/ui_run_case.py", line 10, in <module>
    from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/home/wouter/Environments/StratosIV/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "matplotlib/backends/__init__.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/home/wouter/Environments/StratosIV/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "matplotlib/backend_bases.py", line 46, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/home/wouter/Environments/StratosIV/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "matplotlib/textpath.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/home/wouter/Environments/StratosIV/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "matplotlib/font_manager.py", line 1366, in <module>
  File "matplotlib/font_manager.py", line 1347, in _rebuild
  File "matplotlib/font_manager.py", line 981, in __init__
  File "matplotlib/font_manager.py", line 270, in findSystemFonts
  File "matplotlib/font_manager.py", line 248, in get_fontconfig_fonts
  File "matplotlib/font_manager.py", line 236, in _call_fc_list
  File "subprocess.py", line 336, in check_output
  File "subprocess.py", line 403, in run
  File "subprocess.py", line 707, in __init__
  File "subprocess.py", line 1260, in _execute_child
TypeError: fork_exec() argument 4 must be tuple, not list
[3664] Failed to execute script main
```
My suspicion is that it has something to do with matplotlib, but looking through Stackoverflow did not result in me finding a solution to this problem (I was changing values in the font_manager.py of matplotlib but this did not help).

My system/program specifications are:
* Ubuntu 16.04
* Python 3.6.0
* Matplotlib version 3.1.0
* fbs version 0.8.3
* PyInstaller version 3.4
* PyQt5 version 5.12.2

An example code that result in this error, when trying to execute the application after freeze is (from [https://matplotlib.org/examples/user_interfaces/embedding_in_qt5.html](url) )

```from __future__ import unicode_literals
import sys
import os
import random
import matplotlib
# Make sure that we are using QT5
matplotlib.use('Qt5Agg')
from PyQt5 import QtCore, QtWidgets

from numpy import arange, sin, pi
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.figure import Figure

progname = os.path.basename(sys.argv[0])
progversion = "0.1"


class MyMplCanvas(FigureCanvas):
    """Ultimately, this is a QWidget (as well as a FigureCanvasAgg, etc.)."""

    def __init__(self, parent=None, width=5, height=4, dpi=100):
        fig = Figure(figsize=(width, height), dpi=dpi)
        self.axes = fig.add_subplot(111)

        self.compute_initial_figure()

        FigureCanvas.__init__(self, fig)
        self.setParent(parent)

        FigureCanvas.setSizePolicy(self,
                                   QtWidgets.QSizePolicy.Expanding,
                                   QtWidgets.QSizePolicy.Expanding)
        FigureCanvas.updateGeometry(self)

    def compute_initial_figure(self):
        pass


class MyStaticMplCanvas(MyMplCanvas):
    """Simple canvas with a sine plot."""

    def compute_initial_figure(self):
        t = arange(0.0, 3.0, 0.01)
        s = sin(2*pi*t)
        self.axes.plot(t, s)


class MyDynamicMplCanvas(MyMplCanvas):
    """A canvas that updates itself every second with a new plot."""

    def __init__(self, *args, **kwargs):
        MyMplCanvas.__init__(self, *args, **kwargs)
        timer = QtCore.QTimer(self)
        timer.timeout.connect(self.update_figure)
        timer.start(1000)

    def compute_initial_figure(self):
        self.axes.plot([0, 1, 2, 3], [1, 2, 0, 4], 'r')

    def update_figure(self):
        # Build a list of 4 random integers between 0 and 10 (both inclusive)
        l = [random.randint(0, 10) for i in range(4)]
        self.axes.cla()
        self.axes.plot([0, 1, 2, 3], l, 'r')
        self.draw()


class ApplicationWindow(QtWidgets.QMainWindow):
    def __init__(self):
        QtWidgets.QMainWindow.__init__(self)
        self.setAttribute(QtCore.Qt.WA_DeleteOnClose)
        self.setWindowTitle("application main window")

        self.file_menu = QtWidgets.QMenu('&File', self)
        self.file_menu.addAction('&Quit', self.fileQuit,
                                 QtCore.Qt.CTRL + QtCore.Qt.Key_Q)
        self.menuBar().addMenu(self.file_menu)

        self.help_menu = QtWidgets.QMenu('&Help', self)
        self.menuBar().addSeparator()
        self.menuBar().addMenu(self.help_menu)

        self.help_menu.addAction('&About', self.about)

        self.main_widget = QtWidgets.QWidget(self)

        l = QtWidgets.QVBoxLayout(self.main_widget)
        sc = MyStaticMplCanvas(self.main_widget, width=5, height=4, dpi=100)
        dc = MyDynamicMplCanvas(self.main_widget, width=5, height=4, dpi=100)
        l.addWidget(sc)
        l.addWidget(dc)

        self.main_widget.setFocus()
        self.setCentralWidget(self.main_widget)

        self.statusBar().showMessage("All hail matplotlib!", 2000)

    def fileQuit(self):
        self.close()

    def closeEvent(self, ce):
        self.fileQuit()

    def about(self):
        QtWidgets.QMessageBox.about(self, "About",
                                    """embedding_in_qt5.py example
Copyright 2005 Florent Rougon, 2006 Darren Dale, 2015 Jens H Nielsen

This program is a simple example of a Qt5 application embedding matplotlib
canvases.

It may be used and modified with no restriction; raw copies as well as
modified versions may be distributed without limitation.

This is modified from the embedding in qt4 example to show the difference
between qt4 and qt5"""
                                )```

Thanks in advance for any help!

**Comment by mherrmann** [comment]
Sorry, I don't have time to read all this code. Can you come up with a simpler example that shows that the problem is truly caused by fbs?

**Comment by wjhuisman** [comment]
Yes, my apologies. I have added a sample script which produces the same error. 

```
from PyQt5.QtWidgets import *

import matplotlib
matplotlib.use('Qt5Agg')
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.figure import Figure
import matplotlib.pyplot as plt
import numpy as np

def simple_plot():
    # Data for plotting
    t = np.arange(0.0, 2.0, 0.01)
    s = 1 + np.sin(2 * np.pi * t)

    fig, ax = plt.subplots()
    ax.plot(t, s)

    ax.set(xlabel='time (s)', ylabel='voltage (mV)',
           title='About as simple as it gets, folks')
    ax.grid()
    return fig

class MyMplCanvas(FigureCanvas):
    # More information about this part can be found at: https://matplotlib.org/examples/user_interfaces/embedding_in_qt5.html
    def __init__(self):
        self.fig = Figure()
        self.axes = self.fig.add_subplot(111)

        self.compute_initial_figure()

        FigureCanvas.__init__(self, self.fig)

        FigureCanvas.setSizePolicy(self, QSizePolicy.Expanding, QSizePolicy.Expanding)
        FigureCanvas.updateGeometry(self)

    def compute_initial_figure(self):
        pass

"""Use the static canvas as a dynamic canvas so figures can be replotted"""
class MyDynamicCanvas(MyMplCanvas):
    # More information about this part can be found at: https://matplotlib.org/examples/user_interfaces/embedding_in_qt5.html
    def __init__(self, *args, **kwargs):
        MyMplCanvas.__init__(self, *args, **kwargs)

    def update_figure(self, fig):
        self.figure = fig
        self.draw()

class ApplicationWindow(QWidget):
    def __init__(self):
        super(ApplicationWindow, self).__init__()

        # Create layout and widgets
        gridLayout = QGridLayout(self)
        pushButton = QPushButton("Click me to plot figure")
        self.canvas = MyDynamicCanvas()

        # Add widgets to layout
        gridLayout.addWidget(pushButton)
        gridLayout.addWidget(self.canvas)

        # Add action to push button
        pushButton.clicked.connect(self.on_clicked)

    def on_clicked(self):
        fig = simple_plot()
        self.canvas.update_figure(fig)


```

The class `MyDynamicCanvas` is a class which allows a matplotlib to be updated when the pushbutton is clicked. This is crucial for my application, and is a suspicion of mine that causes the problem.

**Comment by mherrmann** [comment]
I can't reproduce this, sorry. I had to install the `develop` version of PyInstaller. I'm using PyQt5 5.9.2 and am on Xfce (similar to Ubuntu). Everything works fine for me. When I click the button, the figure is plotted. Does the problem for you when you start from a fresh virtual environment and the following `pip` command?

    pip install fbs==0.8.3 PyQt5==5.9.2 matplotlib==3.0.3 https://github.com/pyinstaller/pyinstaller/archive/develop.tar.gz

**Comment by wjhuisman** [comment]
I started from a fresh virtual environment and after running your pip command I got the following packages:
- altgraph        0.16.1            
- cycler          0.10.0            
- fbs             0.8.3             
- kiwisolver      1.1.0             
- matplotlib      3.0.3             
- numpy           1.16.4            
- pip             19.0.3            
- PyInstaller     3.5.dev0+9e1f05ba2
- pyparsing       2.4.0             
- PyQt5           5.9.2             
- python-dateutil 2.8.0             
- setuptools      40.8.0            
- sip             4.19.8            
- six             1.12.0 

Sadly, the error still remains after I freeze (successfully) and run the application (using : `./target/GUI-test/GUI-test`). I'll try to run the same script on my windows installation, maybe that will give us some insight.

**Comment by wjhuisman** [comment]
After freezing the application on my Windows installation, the program works when I run the .exe file. I would still want it to work on my Linux installation as well. Do you have any suspicion what the problem might be?

**Comment by mherrmann** [comment]
I don't know, sorry. There seems to be a [matplotlib bug](https://github.com/matplotlib/matplotlib/issues/12173/) related to this. If it helps, I have slightly different libraries after my `pip` commands:

```altgraph==0.16.1
cycler==0.10.0
fbs==0.8.3
future==0.17.1
kiwisolver==1.1.0
macholib==1.11
matplotlib==3.0.3
numpy==1.16.4
pefile==2019.4.18
pkg-resources==0.0.0
PyInstaller==3.5.dev0+9e1f05ba2
pyparsing==2.4.0
PyQt5==5.9.2
python-dateutil==2.8.0
sip==4.19.8
six==1.12.0```
