### ISSUE TITLE
WinError 2 on fbs freeze

### ISSUE THREAD

**Issue by sstucker** [mherrmann/fbs#127]
Fresh install of Python 3.6.7 on 64-bit Windows 10
pip freeze:
```
altgraph==0.16.1
fbs==0.8.3
future==0.17.1
macholib==1.11
numpy==1.16.4
pefile==2019.4.18
PyInstaller==3.4
PyQt5==5.9.2
pyqtgraph==0.10.0
pywin32-ctypes==0.2.0
sip==4.19.8
```
Occurs when trying to freeze right after a new ```startproject```
fbs run works just fine, but fbs freeze --debug gives:
```
C:\Users\sstucker\OneDrive\Documents\PyImageOCT>C:\Users\sstucker\Python36\python -m fbs freeze --debug
Traceback (most recent call last):
  File "C:\Users\sstucker\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\sstucker\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\sstucker\Python36\lib\site-packages\fbs\__main__.py", line 50, in <module>
    _main()
  File "C:\Users\sstucker\Python36\lib\site-packages\fbs\__main__.py", line 17, in _main
    fbs.cmdline.main()
  File "C:\Users\sstucker\Python36\lib\site-packages\fbs\cmdline.py", line 32, in main
    fn(*args)
  File "C:\Users\sstucker\Python36\lib\site-packages\fbs\builtin_commands\__init__.py", line 120, in freeze
    freeze_windows(debug=debug)
  File "C:\Users\sstucker\Python36\lib\site-packages\fbs\freeze\windows.py", line 18, in freeze_windows
    run_pyinstaller(args, debug)
  File "C:\Users\sstucker\Python36\lib\site-packages\fbs\freeze\__init__.py", line 48, in run_pyinstaller
    run(args, check=True)
  File "C:\Users\sstucker\Python36\lib\subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\sstucker\Python36\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Users\sstucker\Python36\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

A PyInstaller issue?

**Comment by mherrmann** [comment]
What happens when you type just `pyinstaller` on the command line?

**Comment by sstucker** [comment]
Turns out PyInstaller wasn't properly installed. [This ](https://stackoverflow.com/a/54338665/11540004)helped and so did installing [Windows 10 SDK](https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk). Thanks!

**Comment by mherrmann** [comment]
Happy to hear it works now :-)
