### ISSUE TITLE
I got this error while fbs freeze ""PermissionError: [WinError 5] Access is denied:"" how can i solve this issue. 

### ISSUE THREAD

**Issue by Prady96** [mherrmann/fbs#129]

**Comment by himanshus97** [comment]
I'm getting similar error how should i resolve it ...

**Comment by himanshus97** [comment]
here is the error copied 

````
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\YouSly\\Desktop\\finalApp\\target\\YouSly'
Traceback (most recent call last):
  File "C:\Users\YouSly\Desktop\finalApp\venv\Scripts\fbs-script.py", line 11, in <module>
    load_entry_point('fbs==0.8.3', 'console_scripts', 'fbs')()
  File "c:\users\yously\desktop\finalapp\venv\lib\site-packages\fbs\__main__.py", line 17, in _main
    fbs.cmdline.main()
  File "c:\users\yously\desktop\finalapp\venv\lib\site-packages\fbs\cmdline.py", line 32, in main
    fn(*args)
  File "c:\users\yously\desktop\finalapp\venv\lib\site-packages\fbs\builtin_commands\__init__.py", line 120, in freeze
    freeze_windows(debug=debug)
  File "c:\users\yously\desktop\finalapp\venv\lib\site-packages\fbs\freeze\windows.py", line 18, in freeze_windows
    run_pyinstaller(args, debug)
  File "c:\users\yously\desktop\finalapp\venv\lib\site-packages\fbs\freeze\__init__.py", line 48, in run_pyinstaller
    run(args, check=True)
  File "C:\Users\YouSly\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['pyinstaller', '--name', 'YouSly', '--noupx', '--log-level', 'DEBUG', '--noconfirm', '--hidden-import', 'threading', '--hidden-import', 'urllib', '--hidden-import', 'PIL', '--hidden-import', 'face_recognition', '--hidden-import', 'numpy', '--hidden-import', 'pythoncom', '--hidden-import', 'requests', '--hidden-import', 'pyHook', '--hidden-import', 'json', '--hidden-import', 'cv2', '--hidden-import', 'sys', '--icon', 'C:\\Users\\YouSly\\Desktop\\finalApp\\src\\main\\icons\\Icon.ico', '--distpath', 'C:\\Users\\YouSly\\Desktop\\finalApp\\target', '--specpath', 'C:\\Users\\YouSly\\Desktop\\finalApp\\target\\PyInstaller', '--workpath', 'C:\\Users\\YouSly\\Desktop\\finalApp\\target\\PyInstaller', '--additional-hooks-dir', 'c:\\users\\yously\\desktop\\finalapp\\venv\\lib\\site-packages\\fbs\\freeze\\hooks', '--debug', 'all', '--runtime-hook', 'C:\\Users\\YouSly\\AppData\\Local\\Temp\\tmp3gxbkwe_\\fbs_pyinstaller_hook.py', 'C:\\Users\\YouSly\\Desktop\\finalApp\\src\\main\\python\\main.py']' returned non-zero exit status 1.
````

**Comment by himanshus97** [comment]
let me know if i require to paste any things

Thanking you in advance

**Comment by Andharikar9011** [comment]
plz anyone if possible provide a solution coz installed everything as said but same error

**Comment by mherrmann** [comment]
There is not enough information in this thread for me to be able to help you. Which code are you all using? Does the problem already appear when you do:

    fbs startproject
    fbs freeze

?

**Comment by Prady96** [comment]
There was an error in my subprocess command, therefore this error raised,
As subprocess is deprecated now os.system is being used.

Thanks for support
