### ISSUE TITLE
Relative path module not found in fbs freeze

### ISSUE THREAD

**Issue by sthuq** [mherrmann/fbs#158]
When I launch the exe created by fbs freeze, I get the following error: 
```
import 'logging' # <_frozen_importlib_external.SourcelessFileLoader object at 0x04332590>
# contollers not found in PYZ
Traceback (most recent call last):
  File "python\app.py", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'contollers'
```
My directory structure is as follows:
```
- main.py
-__init__.py
-- contollers
-- submod1.py
-- submod2.py
-- __init__.py
--- helpers
--- helpers1.py
--- helpers2.py
--- __init__.py
```

I am launching from the exe from inside target\AppName
fbs run works fine so I suspect the pathing is problematic. What is the root path that is seen when the exe is launched? 

my base.json settings:
```json
{
    "app_name": "DummyApp",
    "author": "DummyInc",
    "main_module": "src/main/python/main.py",
    "version": "0.0.0"
}
```

**Comment by sthuq** [comment]
I solved this problem by removing the __init__.py at the main folder.

I need some guidance on how to let fbs know how to copy non py files into the directory specified under hidden_imports. Are there other settings I can use for this task?

**Comment by sthuq** [comment]
Closing this as the problem is solved
