### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'C:...\\astor\\VERSION'

### ISSUE THREAD

**Issue by dadanhan** [mherrmann/fbs#168]
Hi,

I am getting an error from running the .exe file generated from `fbs freeze`, even though `fbs run` works. I have followed the steps at https://build-system.fman.io/troubleshooting and I still get an error. I think it's something to do with tensorflow and the package astor but I don't have the understanding to figure out what is going wrong (I've spent ages looking at other similar errors on stackoverflow/github and still can't figure it out).

 * My operating system:  Windows 10
 * My Python version: Python 3.6.8
 * My fbs version: 0.8.4
 * My PyInstaller version: 3.4
 * My PyQt5 version: 5.9.2
 * Additional installed package versions: 
     tensorflow: 2.1.0
     setuptools: 44.0.0
     astor: 0.8.1
 * Here is a copy of my error messages that I get from running the .exe file after fbs freeze --debug:
```
2020-01-14 20:08:15.446084: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
Traceback (most recent call last):
  File "main.py", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\work\fbmapplication\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "lib\site-packages\tensorflow\__init__.py", line 40, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\work\fbmapplication\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "lib\site-packages\tensorflow\python\__init__.py", line 85, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\work\fbmapplication\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "lib\site-packages\tensorflow\python\ops\standard_ops.py", line 26, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\work\fbmapplication\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "lib\site-packages\tensorflow\python\autograph\__init__.py", line 37, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\work\fbmapplication\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "lib\site-packages\tensorflow\python\autograph\core\converter.py", line 71, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\work\fbmapplication\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "lib\site-packages\tensorflow\python\autograph\pyct\cfg.py", line 41, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\work\fbmapplication\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "lib\site-packages\tensorflow\python\autograph\pyct\compiler.py", line 32, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\work\fbmapplication\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "lib\site-packages\astor\__init__.py", line 24, in <module>
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Work\\fbmapplication\\target\\DLFNN Exponent Estimator\\astor\\VERSION'
[32] Failed to execute script main
```

 * Here is a minimal script that reproduces the problem I am experiencing:
```
from fbs_runtime.application_context.PyQt5 import ApplicationContext
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QObject, pyqtSlot

import sys
import os
import pandas as pd
from fbm import FBM
import numpy as np
from random import uniform
import tensorflow as tf

if __name__ == '__main__':
    appctxt = ApplicationContext()       # 1. Instantiate ApplicationContext
    window = QtWidgets.QMainWindow()
    window.resize(250, 150)
    window.show()
    exit_code = appctxt.app.exec_()      # 2. Invoke appctxt.app.exec_()
    sys.exit(exit_code)
```

The funny thing is that I thought it was a dependency problem since when I run `fbs freeze`,  I do not see the folder `\MyApp\target\MyApp\astor` so I tried adding:
"hidden imports": ["astor"]
to `base.json` but that gives me an error when running fbs freeze:
```
...
83592 INFO: Building EXE from EXE-00.toc completed successfully.
83597 INFO: checking COLLECT
83611 INFO: Removing dir C:...\MyApp (most recent call last):
  File "C:\\...\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\\...\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\...\venv\scripts\pyinstaller.exe\__main__.py", line 9, in <module>
  File "c:\...\venv\lib\site-packages\PyInstaller\__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\...\venv\lib\site-packages\PyInstaller\__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\...\venv\lib\site-packages\PyInstaller\building\build_main.py", line 838, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\...\venv\lib\site-packages\PyInstaller\building\build_main.py", line 784, in build
    exec(text, spec_namespace)
  File "<string>", line 36, in <module>
  File "c:\...\venv\lib\site-packages\PyInstaller\building\api.py", line 676, in __init__
    self.__postinit__()
  File "c:\...\venv\lib\site-packages\PyInstaller\building\datastruct.py", line 158, in __postinit__
    self.assemble()
  File "c:\...\venv\lib\site-packages\PyInstaller\building\api.py", line 689, in assemble
    _make_clean_directory(self.name)
  File "c:\...\venv\lib\site-packages\PyInstaller\building\utils.py", line 413, in _make_clean_directory
    os.makedirs(path)
  File "C:\...\AppData\Local\Programs\Python\Python36\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [WinError 5] Access is denied: 'C:\\Work\\MyApp\\target\\MyApp'
Traceback (most recent call last):
  File "C:\...\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\...\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\...\venv\Scripts\fbs.exe\__main__.py", line 9, in <module>
  File "c:\...\venv\lib\site-packages\fbs\__main__.py", line 17, in _main
    fbs.cmdline.main()
  File "c:\...\venv\lib\site-packages\fbs\cmdline.py", line 32, in main
    fn(*args)
  File "c:\...\venv\lib\site-packages\fbs\builtin_commands\__init__.py", line 120, in freeze
    freeze_windows(debug=debug)
  File "c:\...\venv\lib\site-packages\fbs\freeze\windows.py", line 18, in freeze_windows
    run_pyinstaller(args, debug)
  File "c:\...\venv\lib\site-packages\fbs\freeze\__init__.py", line 47, in run_pyinstaller
    run(args, check=True)
  File "C:\...\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['pyinstaller', '--name', 'DLFNN Exponent Estimator', '--noupx', '--log-level', 'DEBUG', '--noconfirm', '--hidden-import', 'astor', '--icon', 'C:\\...\\src\\main\\icons\\Icon.ico', '--distpath', 'C:\\...\\target', '--specpath', 'C:\\...\\target\\PyInstaller', '--workpath', 'C:\\...\\target\\PyInstaller', '--additional-hooks-dir', 'c:\\...\\venv\\lib\\site-packages\\fbs\\freeze\\hooks', '--debug', 'all', '--runtime-hook', 'C:\\...\\target\\PyInstaller\\fbs_pyinstaller_hook.py', 'C:\\...\\src\\main\\python\\main.py']' returned non-zero exit status 1.
```

I really appreciate any pointers you can give me since I have been stuck at this for a while. Sorry for the long post and thanks for any help!

Thanks,

Daniel

**Comment by lsox** [comment]
I have a similar issue, but can't even get through the `fbs freeze` process. I used fbs to create a .exe successfully a few months ago. One thing I added to my code since then is a `import pandas as pd` line, which you also have...

**Comment by j9ac9k** [comment]
I think pyinstaller going from 3.5 -> 3.6 causes issues with `fbs`; I pinned my pyinstaller version to 3.5 and I've been good, but I've been meaning to look into this a bit more and ideally submit a PR for a fix to address this issue.

**Comment by dadanhan** [comment]
So after playing around with various packages and installations, I was able to get the fbs freeze and fbs installer working using the following:

*My operating system: Windows 10
*My Python version: Python 3.5.4rc1 (downloaded from python directly)
*My fbs version: 0.8.4
*My PyInstaller version: 3.4
*My PyQt5 version: 5.9.2
*tensorflow: 1.12.0
*setuptools: 39.1.0
*astor: 0.8.1

**Comment by Kpheer** [comment]
Can you solve it on tensorflow 2?

**Comment by da-pang-za** [comment]
I chaged astor==0.8.1 to  astor==0.8.0,and my program could work.

**Comment by chandlerfan777** [comment]
Hi,
I meet a similar problem. Your solution helps me. Thank you!!

Best Regards,
Chandler Fan
