### ISSUE TITLE
fbs incompatible with pyinstaller 3.6

### ISSUE THREAD

**Issue by vincentlaval31** [mherrmann/fbs#169]
Hello, 
I'm sorry but I tried with several versions of python and as you say with 3.6.5, but I always get this error message when I do fbs freeze?
can you help me ? Thank you.
![Capture d’écran 2020-01-18 à 16 44 01](https://user-images.githubusercontent.com/54274206/72666424-6d8cfc80-3a12-11ea-8756-4574eeb63abb.png)

**Comment by phablulo** [comment]
Same issue on Ubuntu 19.10, Python 3.7.5

**Comment by axhe** [comment]
I see the same issue on Windows 10. 

It seems to be an issue with PyInstaller 3.6 which was released some days ago. As a workaround downgrade it to 3.5 in your requirements.txt:
`PyInstaller==3.5`

**Comment by vincentlaval31** [comment]
Thank's a lot, the issue is resolved with the PyInstaller 3.5 !!

**Comment by ThibH** [comment]
Indeed, not working with PyInstaller 3.6.
To downgrade to PyInstaller 3.5 you can use `pip install --upgrade PyInstaller==3.5`.

**Comment by ryanseghers** [comment]
I failed to find this issue in a search because all the relevant keywords are in a screenshot, so here are some:
imphook.py AssertionError
assert self.hook_module_name not in HOOKS_MODULE_NAMES

And the duplicate module name appears to be "__PyInstaller_hooks_0_PySide2"

**Comment by j9ac9k** [comment]
@vincentlaval31 may I suggest you rename the issue to something along the lines of

> fbs incompatible with pyinstaller 3.6

**Comment by Aperion** [comment]
This appears to be a naming conflict between `hooks-PySide2.py` provided by fbs and PyInstaller. Renaming the file from `hook-PySide2.py` to `hook-PySide2_fbs.py` in the `fbs/freeze/hooks directory`  install directory. This allows the freeze to complete.Though i''m not completely sure of what effects it will have. I'm still investigating.

**Comment by mherrmann** [comment]
I fixed this in release 0.8.5, by pinning fbs's required PyInstaller version to 3.4.

**Comment by jprouty** [comment]
This is not fixing the actual issue. Considering that there's a high severity vulnerability with [PyInstaller < 3.6](https://github.com/advisories/GHSA-7fcj-pq9j-wh2r), I would love to see a solution to get onto  =< 3.6 properly (ie, keep this issue open until fbs supports pyinstall 3.6).

Similarly, I've been able to successfully build with PyInstaller 3.5 on all 3 platforms w/ Py 3.7 with no issue. Not sure why we'd want to pin to 3.4 specifically, as others (on this issue itself) have indicated 3.5 have fixed their issue.

**Comment by ryanseghers** [comment]
Also note that fbs 0.8.5 breaks my build (Windows, Python 3.7.5, yes I know unsupported config) presumably because of PyInstaller 3.4. Reverting to 0.8.4 fixes the problem.

**Comment by mherrmann** [comment]
>  Considering that there's a high severity vulnerability with PyInstaller < 3.6

The vulnerability you mention says:

> If a software frozen by PyInstaller in "onefile" mode [...]

fbs does not use onefile mode, hence is not affected by the vulnerability.

> I've been able to successfully build with PyInstaller 3.5 on all 3 platforms w/ Py 3.7

I don't understand why you would even try this when fbs explicitly does not support these versions.

> Python 3.7.5, yes I know unsupported config

Yes, it is unsupported.

fbs works because I use it in [fman](https://fman.io) on tens of thousands of machines. There have been cases where errors - to do with specific Python versions - only showed up in 1/1000 users. By pinning the exact versions (Python 3.6 / PyInstaller 3.4) that I use in fman, I can guarantee that things will work. I do not have time to give this guarantee for other version combinations. Hence, I do not support them.

**Comment by ryanseghers** [comment]
@mherrmann It seems fair to limit support to older versions of Python. I am operating at my own risk on Python 3.7.5. Thanks for all your excellent work on fbs.

**Comment by mherrmann** [comment]
Thank you for your understanding @ryanseghers :-)

**Comment by jgirardet** [comment]
Hi, I'm reading this thread, python 3.6.10, fbs 8.6 and pysid2 2 5.14.2
same error :
```
(.venv) jimmy@cacahuete:~/dev/cacahuete/MyCartable$ fbs freeze
Traceback (most recent call last):
  File "/home/jimmy/dev/cacahuete/MyCartable/.venv/bin/pyinstaller", line 8, in <module>
    sys.exit(run())
  File "/home/jimmy/dev/cacahuete/MyCartable/.venv/lib/python3.6/site-packages/PyInstaller/__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/home/jimmy/dev/cacahuete/MyCartable/.venv/lib/python3.6/site-packages/PyInstaller/__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/home/jimmy/dev/cacahuete/MyCartable/.venv/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 838, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/home/jimmy/dev/cacahuete/MyCartable/.venv/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 784, in build
    exec(text, spec_namespace)
  File "<string>", line 17, in <module>
  File "/home/jimmy/dev/cacahuete/MyCartable/.venv/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 241, in __init__
    self.__postinit__()
  File "/home/jimmy/dev/cacahuete/MyCartable/.venv/lib/python3.6/site-packages/PyInstaller/building/datastruct.py", line 158, in __postinit__
    self.assemble()
  File "/home/jimmy/dev/cacahuete/MyCartable/.venv/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 500, in assemble
    module_hook.post_graph()
  File "/home/jimmy/dev/cacahuete/MyCartable/.venv/lib/python3.6/site-packages/PyInstaller/building/imphook.py", line 410, in post_graph
    self._load_hook_module()
  File "/home/jimmy/dev/cacahuete/MyCartable/.venv/lib/python3.6/site-packages/PyInstaller/building/imphook.py", line 377, in _load_hook_module
    self.hook_module_name, self.hook_filename)
  File "/home/jimmy/dev/cacahuete/MyCartable/.venv/lib/python3.6/site-packages/PyInstaller/compat.py", line 736, in importlib_load_source
    return mod_loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 823, in load_module
  File "<frozen importlib._bootstrap_external>", line 682, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/jimmy/dev/cacahuete/MyCartable/.venv/lib/python3.6/site-packages/PyInstaller/hooks/hook-PySide2.QtQuick.py", line 13, in <module>
    from PyInstaller.utils.hooks import get_qmake_path, exec_command
ImportError: cannot import name 'exec_command'
Traceback (most recent call last):
  File "/home/jimmy/dev/cacahuete/MyCartable/.venv/bin/fbs", line 11, in <module>
    load_entry_point('fbs==0.8.6', 'console_scripts', 'fbs')()
  File "/home/jimmy/dev/cacahuete/MyCartable/.venv/lib/python3.6/site-packages/fbs/__main__.py", line 17, in _main
    fbs.cmdline.main()
  File "/home/jimmy/dev/cacahuete/MyCartable/.venv/lib/python3.6/site-packages/fbs/cmdline.py", line 32, in main
    fn(*args)
  File "/home/jimmy/dev/cacahuete/MyCartable/.venv/lib/python3.6/site-packages/fbs/builtin_commands/__init__.py", line 125, in freeze
    freeze_ubuntu(debug=debug)
  File "/home/jimmy/dev/cacahuete/MyCartable/.venv/lib/python3.6/site-packages/fbs/freeze/ubuntu.py", line 4, in freeze_ubuntu
    freeze_linux(debug)
  File "/home/jimmy/dev/cacahuete/MyCartable/.venv/lib/python3.6/site-packages/fbs/freeze/linux.py", line 8, in freeze_linux
    run_pyinstaller(debug=debug)
  File "/home/jimmy/dev/cacahuete/MyCartable/.venv/lib/python3.6/site-packages/fbs/freeze/__init__.py", line 47, in run_pyinstaller
    run(args, check=True)
  File "/home/jimmy/.pyenv/versions/3.6.10/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['pyinstaller', '--name', 'MyCartable', '--noupx', '--log-level', 'ERROR', '--noconfirm', '--distpath', '/home/jimmy/dev/cacahuete/MyCartable/target', '--specpath', '/home/jimmy/dev/cacahuete/MyCartable/target/PyInstaller', '--workpath', '/home/jimmy/dev/cacahuete/MyCartable/target/PyInstaller', '--additional-hooks-dir', '/home/jimmy/dev/cacahuete/MyCartable/.venv/lib/python3.6/site-packages/fbs/freeze/hooks', '--runtime-hook', '/home/jimmy/dev/cacahuete/MyCartable/target/PyInstaller/fbs_pyinstaller_hook.py', '/home/jimmy/dev/cacahuete/MyCartable/src/main/python/main.py']' returned non-zero exit status 1.
(.venv) jimmy@cacahuete:~/dev/cacahuete/MyCartable$ fbs freeze
Traceback (most recent call last):
  File "/home/jimmy/dev/cacahuete/MyCartable/.venv/bin/pyinstaller", line 8, in <module>
    sys.exit(run())
  File "/home/jimmy/dev/cacahuete/MyCartable/.venv/lib/python3.6/site-packages/PyInstaller/__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/home/jimmy/dev/cacahuete/MyCartable/.venv/lib/python3.6/site-packages/PyInstaller/__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/home/jimmy/dev/cacahuete/MyCartable/.venv/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 838, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/home/jimmy/dev/cacahuete/MyCartable/.venv/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 784, in build
    exec(text, spec_namespace)
  File "<string>", line 17, in <module>
  File "/home/jimmy/dev/cacahuete/MyCartable/.venv/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 241, in __init__
    self.__postinit__()
  File "/home/jimmy/dev/cacahuete/MyCartable/.venv/lib/python3.6/site-packages/PyInstaller/building/datastruct.py", line 158, in __postinit__
    self.assemble()
  File "/home/jimmy/dev/cacahuete/MyCartable/.venv/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 500, in assemble
    module_hook.post_graph()
  File "/home/jimmy/dev/cacahuete/MyCartable/.venv/lib/python3.6/site-packages/PyInstaller/building/imphook.py", line 410, in post_graph
    self._load_hook_module()
  File "/home/jimmy/dev/cacahuete/MyCartable/.venv/lib/python3.6/site-packages/PyInstaller/building/imphook.py", line 377, in _load_hook_module
    self.hook_module_name, self.hook_filename)
  File "/home/jimmy/dev/cacahuete/MyCartable/.venv/lib/python3.6/site-packages/PyInstaller/compat.py", line 736, in importlib_load_source
    return mod_loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 823, in load_module
  File "<frozen importlib._bootstrap_external>", line 682, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/jimmy/dev/cacahuete/MyCartable/.venv/lib/python3.6/site-packages/PyInstaller/hooks/hook-PySide2.QtQuick.py", line 13, in <module>
    from PyInstaller.utils.hooks import get_qmake_path, exec_command
ImportError: cannot import name 'exec_command'
Traceback (most recent call last):
  File "/home/jimmy/dev/cacahuete/MyCartable/.venv/bin/fbs", line 11, in <module>
    load_entry_point('fbs==0.8.6', 'console_scripts', 'fbs')()
  File "/home/jimmy/dev/cacahuete/MyCartable/.venv/lib/python3.6/site-packages/fbs/__main__.py", line 17, in _main
    fbs.cmdline.main()
  File "/home/jimmy/dev/cacahuete/MyCartable/.venv/lib/python3.6/site-packages/fbs/cmdline.py", line 32, in main
    fn(*args)
  File "/home/jimmy/dev/cacahuete/MyCartable/.venv/lib/python3.6/site-packages/fbs/builtin_commands/__init__.py", line 125, in freeze
    freeze_ubuntu(debug=debug)
  File "/home/jimmy/dev/cacahuete/MyCartable/.venv/lib/python3.6/site-packages/fbs/freeze/ubuntu.py", line 4, in freeze_ubuntu
    freeze_linux(debug)
  File "/home/jimmy/dev/cacahuete/MyCartable/.venv/lib/python3.6/site-packages/fbs/freeze/linux.py", line 8, in freeze_linux
    run_pyinstaller(debug=debug)
  File "/home/jimmy/dev/cacahuete/MyCartable/.venv/lib/python3.6/site-packages/fbs/freeze/__init__.py", line 47, in run_pyinstaller
    run(args, check=True)
  File "/home/jimmy/.pyenv/versions/3.6.10/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['pyinstaller', '--name', 'MyCartable', '--noupx', '--log-level', 'ERROR', '--noconfirm', '--distpath', '/home/jimmy/dev/cacahuete/MyCartable/target', '--specpath', '/home/jimmy/dev/cacahuete/MyCartable/target/PyInstaller', '--workpath', '/home/jimmy/dev/cacahuete/MyCartable/target/PyInstaller', '--additional-hooks-dir', '/home/jimmy/dev/cacahuete/MyCartable/.venv/lib/python3.6/site-packages/fbs/freeze/hooks', '--runtime-hook', '/home/jimmy/dev/cacahuete/MyCartable/target/PyInstaller/fbs_pyinstaller_hook.py', '/home/jimmy/dev/cacahuete/MyCartable/src/main/python/main.py']' returned non-zero exit status 1.
```

various fix changing hook name doesn't work

**Comment by Chang-Hoon** [comment]
I tried all above mentioned - `PyInstaller` 3.5/3.4, `Python` 3.6.x etc but it didn't work.

With `pip install fbs-tutorial`, it (re)installs proper versions of packages and runs OK.
