### ISSUE TITLE
Fix fbs freeze failed when we use PySide2

### ISSUE THREAD

**Issue by loonghao** [mherrmann/fbs#171]
**environment**：
- window-10
- python-3.7
- PySide2-5.14.1
- fbs-0.8.4

**issues logs**:
```
(venv) C:\Users\hao.long\yuki>fbs freeze
Traceback (most recent call last):
  File "D:\pipeline\rez_pipeline\app\ext\python\3.7.4\platform-windows\!python_embedded\lib\runpy.py", line 193, in _run_module_as_
main
    "__main__", mod_spec)
  File "D:\pipeline\rez_pipeline\app\ext\python\3.7.4\platform-windows\!python_embedded\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\hao.long\yuki\venv\Scripts\pyinstaller.exe\__main__.py", line 9, in <module>
  File "c:\users\hao.long\yuki\venv\lib\site-packages\PyInstaller\__main__.py", line 114, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\users\hao.long\yuki\venv\lib\site-packages\PyInstaller\__main__.py", line 65, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\users\hao.long\yuki\venv\lib\site-packages\PyInstaller\building\build_main.py", line 734, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\users\hao.long\yuki\venv\lib\site-packages\PyInstaller\building\build_main.py", line 681, in build
    exec(code, spec_namespace)
  File "C:\Users\hao.long\yuki\target\PyInstaller\yuki.spec", line 17, in <module>
    noarchive=False)
  File "c:\users\hao.long\yuki\venv\lib\site-packages\PyInstaller\building\build_main.py", line 244, in __init__
    self.__postinit__()
  File "c:\users\hao.long\yuki\venv\lib\site-packages\PyInstaller\building\datastruct.py", line 160, in __postinit__
    self.assemble()
  File "c:\users\hao.long\yuki\venv\lib\site-packages\PyInstaller\building\build_main.py", line 343, in assemble
    excludes=self.excludes, user_hook_dirs=self.hookspath)
  File "c:\users\hao.long\yuki\venv\lib\site-packages\PyInstaller\depend\analysis.py", line 734, in initialize_modgraph
    user_hook_dirs=user_hook_dirs,
  File "c:\users\hao.long\yuki\venv\lib\site-packages\PyInstaller\depend\analysis.py", line 116, in __init__
    self._reset(user_hook_dirs)
  File "c:\users\hao.long\yuki\venv\lib\site-packages\PyInstaller\depend\analysis.py", line 134, in _reset
    self._hooks = self._cache_hooks("")
  File "c:\users\hao.long\yuki\venv\lib\site-packages\PyInstaller\depend\analysis.py", line 215, in _cache_hooks
    return ModuleHookCache(self, hook_dirs)
  File "c:\users\hao.long\yuki\venv\lib\site-packages\PyInstaller\depend\imphook.py", line 100, in __init__
    self._cache_hook_dirs(hook_dirs)
  File "c:\users\hao.long\yuki\venv\lib\site-packages\PyInstaller\depend\imphook.py", line 133, in _cache_hook_dirs
    hook_module_name_prefix=self._hook_module_name_prefix,
  File "c:\users\hao.long\yuki\venv\lib\site-packages\PyInstaller\depend\imphook.py", line 289, in __init__
    assert self.hook_module_name not in HOOKS_MODULE_NAMES
AssertionError
Traceback (most recent call last):
  File "D:\pipeline\rez_pipeline\app\ext\python\3.7.4\platform-windows\!python_embedded\lib\runpy.py", line 193, in _run_module_as_
main
    "__main__", mod_spec)
  File "D:\pipeline\rez_pipeline\app\ext\python\3.7.4\platform-windows\!python_embedded\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\hao.long\yuki\venv\Scripts\fbs.exe\__main__.py", line 9, in <module>
  File "c:\users\hao.long\yuki\venv\lib\site-packages\fbs\__main__.py", line 17, in _main
    fbs.cmdline.main()
  File "c:\users\hao.long\yuki\venv\lib\site-packages\fbs\cmdline.py", line 32, in main
    fn(*args)
  File "c:\users\hao.long\yuki\venv\lib\site-packages\fbs\builtin_commands\__init__.py", line 120, in freeze
    freeze_windows(debug=debug)
  File "c:\users\hao.long\yuki\venv\lib\site-packages\fbs\freeze\windows.py", line 18, in freeze_windows
    run_pyinstaller(args, debug)
  File "c:\users\hao.long\yuki\venv\lib\site-packages\fbs\freeze\__init__.py", line 47, in run_pyinstaller
    run(args, check=True)
  File "D:\pipeline\rez_pipeline\app\ext\python\3.7.4\platform-windows\!python_embedded\lib\subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['pyinstaller', '--name', 'yuki', '--noupx', '--log-level', 'ERROR', '--noconfirm', '--wind
owed', '--icon', 'C:\\Users\\hao.long\\yuki\\src\\main\\icons\\Icon.ico', '--distpath', 'C:\\Users\\hao.long\\yuki\\target', '--spe
cpath', 'C:\\Users\\hao.long\\yuki\\target\\PyInstaller', '--workpath', 'C:\\Users\\hao.long\\yuki\\target\\PyInstaller', '--additi
onal-hooks-dir', 'c:\\users\\hao.long\\yuki\\venv\\lib\\site-packages\\fbs\\freeze\\hooks', '--runtime-hook', 'C:\\Users\\hao.long\
\yuki\\target\\PyInstaller\\fbs_pyinstaller_hook.py', 'C:\\Users\\hao.long\\yuki\\src\\main\\python\\app.py']' returned non-zero ex
it status 1.
```
**fix**:
![image](https://user-images.githubusercontent.com/13111745/73853196-703d7d80-486b-11ea-900b-f21b38e1ce56.png)

**Comment by DraugurHundur** [comment]
Duplicate of #169

**Comment by loonghao** [comment]
@DraugurHundur Thank you for your tips, but I test use pyinstall-3.5
will get a new error.
```
(venv) C:\Users\hao.long\yuki>fbs freeze
Traceback (most recent call last):
  File "D:\pipeline\rez_pipeline\app\ext\python\3.7.4\platform-windows\!python_embedded\lib\runpy.py", line 193, in _run_module_a
s_main
    "__main__", mod_spec)
  File "D:\pipeline\rez_pipeline\app\ext\python\3.7.4\platform-windows\!python_embedded\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\hao.long\yuki\venv\Scripts\fbs.exe\__main__.py", line 9, in <module>
  File "c:\users\hao.long\yuki\venv\lib\site-packages\fbs\__main__.py", line 17, in _main
    fbs.cmdline.main()
  File "c:\users\hao.long\yuki\venv\lib\site-packages\fbs\cmdline.py", line 32, in main
    fn(*args)
  File "c:\users\hao.long\yuki\venv\lib\site-packages\fbs\builtin_commands\__init__.py", line 120, in freeze
    freeze_windows(debug=debug)
  File "c:\users\hao.long\yuki\venv\lib\site-packages\fbs\freeze\windows.py", line 19, in freeze_windows
    _restore_corrupted_python_dlls()
  File "c:\users\hao.long\yuki\venv\lib\site-packages\fbs\freeze\windows.py", line 38, in _restore_corrupted_python_dlls
    copy(_find_on_path(dll_name), path('${freeze_dir}'))
  File "c:\users\hao.long\yuki\venv\lib\site-packages\fbs\freeze\windows.py", line 92, in _find_on_path
    raise LookupError("Could not find %s on PATH" % file_name)
LookupError: Could not find python3.dll on PATH

(venv) C:\Users\hao.long\yuki>python
Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()
```
use python-3.7 and pyinstaller-3.6 is work fine just need rename `hook-PySide2.py` to `hook-pyside2.py`.

**Comment by DraugurHundur** [comment]
#169 says to rename hook-PySide2.py to hook-PySide2_fbs.py (and that is I believe the same solution as yours). 
Anyway the original exception is the same.

**Comment by loonghao** [comment]
Hi @DraugurHundur I make a quick test rename `hook-PySide2.py` to `hook-PySide2_fbs.py` and I run `fbs freeze` again still failed.
![image](https://user-images.githubusercontent.com/13111745/73960850-8b30f000-4946-11ea-9246-dc942eab4d40.png)

**Comment by loonghao** [comment]
Hi @DraugurHundur I make other tests, #169 mention way is work fine, the error `LookupError: Could not find python3.dll on PATH` is coming from my local venv.

Closing this issue due to duplicate with # 169
