### ISSUE TITLE
fbs freeze fails with python 3.5.0

### ISSUE THREAD

**Issue by saurabhprakash-25** [mherrmann/fbs#175]
Python Version : 3.5.0

fbs freeze gives me the following error

`Traceback (most recent call last):
  File "c:\users\saurabh.prakash\appdata\local\programs\python\python35\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\saurabh.prakash\appdata\local\programs\python\python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\saurabh.prakash\AppData\Local\Programs\Python\Python35\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
  File "c:\users\saurabh.prakash\appdata\local\programs\python\python35\lib\site-packages\PyInstaller\__main__.py", line 114, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\users\saurabh.prakash\appdata\local\programs\python\python35\lib\site-packages\PyInstaller\__main__.py", line 65, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\users\saurabh.prakash\appdata\local\programs\python\python35\lib\site-packages\PyInstaller\building\build_main.py", line 734, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\users\saurabh.prakash\appdata\local\programs\python\python35\lib\site-packages\PyInstaller\building\build_main.py", line 681, in build
    exec(code, spec_namespace)
  File "D:\OneDrive - Tally Solutions Pvt. Ltd\desktop\Tracker\target\PyInstaller\Tracker.spec", line 17, in <module>
    noarchive=False)
  File "c:\users\saurabh.prakash\appdata\local\programs\python\python35\lib\site-packages\PyInstaller\building\build_main.py", line 244, in __init__
    self.__postinit__()
  File "c:\users\saurabh.prakash\appdata\local\programs\python\python35\lib\site-packages\PyInstaller\building\datastruct.py", line 160, in __postinit__
    self.assemble()
  File "c:\users\saurabh.prakash\appdata\local\programs\python\python35\lib\site-packages\PyInstaller\building\build_main.py", line 343, in assemble
    excludes=self.excludes, user_hook_dirs=self.hookspath)
  File "c:\users\saurabh.prakash\appdata\local\programs\python\python35\lib\site-packages\PyInstaller\depend\analysis.py", line 734, in initialize_modgraph
    user_hook_dirs=user_hook_dirs,
  File "c:\users\saurabh.prakash\appdata\local\programs\python\python35\lib\site-packages\PyInstaller\depend\analysis.py", line 116, in __init__
    self._reset(user_hook_dirs)
  File "c:\users\saurabh.prakash\appdata\local\programs\python\python35\lib\site-packages\PyInstaller\depend\analysis.py", line 134, in _reset
    self._hooks = self._cache_hooks("")
  File "c:\users\saurabh.prakash\appdata\local\programs\python\python35\lib\site-packages\PyInstaller\depend\analysis.py", line 215, in _cache_hooks
    return ModuleHookCache(self, hook_dirs)
  File "c:\users\saurabh.prakash\appdata\local\programs\python\python35\lib\site-packages\PyInstaller\depend\imphook.py", line 100, in __init__
    self._cache_hook_dirs(hook_dirs)
  File "c:\users\saurabh.prakash\appdata\local\programs\python\python35\lib\site-packages\PyInstaller\depend\imphook.py", line 133, in _cache_hook_dirs
    hook_module_name_prefix=self._hook_module_name_prefix,
  File "c:\users\saurabh.prakash\appdata\local\programs\python\python35\lib\site-packages\PyInstaller\depend\imphook.py", line 289, in __init__
    assert self.hook_module_name not in HOOKS_MODULE_NAMES
AssertionError
Traceback (most recent call last):
  File "C:\Users\saurabh.prakash\AppData\Local\Programs\Python\Python35\Scripts\fbs-script.py", line 9, in <module>
    load_entry_point('fbs==0.8.4', 'console_scripts', 'fbs')()
  File "c:\users\saurabh.prakash\appdata\local\programs\python\python35\lib\site-packages\fbs\__main__.py", line 17, in _main
    fbs.cmdline.main()
  File "c:\users\saurabh.prakash\appdata\local\programs\python\python35\lib\site-packages\fbs\cmdline.py", line 32, in main
    fn(*args)
  File "c:\users\saurabh.prakash\appdata\local\programs\python\python35\lib\site-packages\fbs\builtin_commands\__init__.py", line 120, in freeze
    freeze_windows(debug=debug)
  File "c:\users\saurabh.prakash\appdata\local\programs\python\python35\lib\site-packages\fbs\freeze\windows.py", line 18, in freeze_windows
    run_pyinstaller(args, debug)
  File "c:\users\saurabh.prakash\appdata\local\programs\python\python35\lib\site-packages\fbs\freeze\__init__.py", line 47, in run_pyinstaller
    run(args, check=True)
  File "c:\users\saurabh.prakash\appdata\local\programs\python\python35\lib\subprocess.py", line 711, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['pyinstaller', '--name', 'Tracker', '--noupx', '--log-level', 'ERROR', '--noconfirm', '--windowed', '--icon', 'D:\\OneDrive - Tally Solutions Pvt. Ltd\\desktop\\Tracker\\src\\main\\icons\\Icon.ico', '--distpath', 'D:\\OneDrive - Tally Solutions Pvt. Ltd\\desktop\\Tracker\\target', '--specpath', 'D:\\OneDrive - Tally Solutions Pvt. Ltd\\desktop\\Tracker\\target\\PyInstaller', '--workpath', 'D:\\OneDrive - Tally Solutions Pvt. Ltd\\desktop\\Tracker\\target\\PyInstaller', '--additional-hooks-dir', 'c:\\users\\saurabh.prakash\\appdata\\local\\programs\\python\\python35\\lib\\site-packages\\fbs\\freeze\\hooks', '--runtime-hook', 'D:\\OneDrive - Tally Solutions Pvt. Ltd\\desktop\\Tracker\\target\\PyInstaller\\fbs_pyinstaller_hook.py', 'D:\\OneDrive - Tally Solutions Pvt. Ltd\\desktop\\Tracker\\src\\main\\python\\main.py']' returned non-zero exit status 1`

**Comment by mherrmann** [comment]
I cannot read this. Also, you didn't specify your PyInstaller version, as asked by the [new issue template](https://github.com/mherrmann/fbs/issues/new).

Closing.
