### ISSUE TITLE
Recursion error

### ISSUE THREAD

**Issue by Jaime02** [mherrmann/fbs#179]
* Windows 10
 * python =3.6.9
 * fbs= 0.8.6
 * PyInstaller = 3.4
 * PyQt5 = 5.9.2

I'm sorry, the output is a huge recursion error, ill cut the repeated parts:

  ```
fbs freeze --debug

Non interesting stuff:

185 INFO: PyInstaller: 3.4
185 INFO: Python: 3.6.8
185 INFO: Platform: Windows-10-10.0.18362-SP0
185 INFO: wrote C:\Users\jaime\Downloads\A\target\PyInstaller\Dibujo tÃ©cnico.spec
185 DEBUG: Testing for UPX ...
185 INFO: UPX is not available.
201 DEBUG: script: C:\Users\jaime\Downloads\A\src\main\python\main.py
201 INFO: Extending PYTHONPATH with paths
['C:\\Users\\jaime\\Downloads\\A\\src\\main\\python',
 'C:\\Users\\jaime\\Downloads\\A\\target\\PyInstaller']
201 INFO: checking Analysis
201 INFO: Building Analysis because Analysis-00.toc is non existent
201 INFO: Initializing module dependency graph...
216 INFO: Initializing module graph hooks...
216 INFO: Analyzing base_library.zip ...
216 DEBUG: Collecting submodules for collections
388 DEBUG: collect_submodules - Found submodules: {'collections.abc', 'collections'}
388 DEBUG: Collecting submodules for encodings
591 DEBUG: collect_submodules - Found submodules: {'encodings.shift_jisx0213', 'encodings.big5', 'encodings.iso8859_1', 'encodings.cp850', 'encodings.euc_jis_2004', 'encodings.mac_greek', 'encodings.iso2022_jp_2', 'encodings.cp860', 'encodings.utf_7', 'encodings.iso2022_jp_3', 'encodings.iso8859_11', 'encodings.quopri_codec', 'encodings.cp857', 'encodings.utf_16_be', 'encodings.mac_turkish', 'encodings.cp1254', 'encodings.base64_codec', 'encodings.idna', 'encodings.cp858', 'encodings.cp437', 'encodings.euc_jisx0213', 'encodings.gb2312', 'encodings.cp65001', 'encodings.mac_roman', 'encodings.raw_unicode_escape', 'encodings.iso2022_jp_1', 'encodings.cp273', 'encodings.iso8859_5', 'encodings.mac_romanian', 'encodings.hex_codec', 'encodings.iso2022_jp_ext', 'encodings.cp932', 'encodings.tis_620', 'encodings.gbk', 'encodings.hp_roman8', 'encodings.cp866', 'encodings.oem', 'encodings.cp1258', 'encodings.iso8859_15', 'encodings.mac_cyrillic', 'encodings.cp720', 'encodings.utf_16_le', 'encodings.cp869', 'encodings.iso8859_2', 'encodings.iso2022_jp_2004', 'encodings.cp852', 'encodings.cp1125', 'encodings.mac_croatian', 'encodings.cp865', 'encodings.shift_jis_2004', 'encodings.cp874', 'encodings.bz2_codec', 'encodings.cp1252', 'encodings.palmos', 'encodings.iso8859_14', 'encodings.mac_iceland', 'encodings', 'encodings.iso8859_16', 'encodings.cp1250', 'encodings.iso8859_4', 'encodings.aliases', 'encodings.mac_farsi', 'encodings.mbcs', 'encodings.cp1251', 'encodings.iso2022_kr', 'encodings.utf_32_be', 'encodings.euc_jp', 'encodings.cp949', 'encodings.cp875', 'encodings.hz', 'encodings.utf_8_sig', 'encodings.cp950', 'encodings.utf_32', 'encodings.cp1257', 'encodings.cp1026', 'encodings.zlib_codec', 'encodings.johab', 'encodings.undefined', 'encodings.mac_centeuro', 'encodings.ptcp154', 'encodings.utf_8', 'encodings.cp1255', 'encodings.iso8859_8', 'encodings.koi8_t', 'encodings.cp424', 'encodings.iso8859_7', 'encodings.uu_codec', 'encodings.iso8859_3', 'encodings.cp1140', 'encodings.cp1256', 'encodings.iso8859_6', 'encodings.rot_13', 'encodings.koi8_u', 'encodings.unicode_escape', 'encodings.cp863', 'encodings.cp500', 'encodings.koi8_r', 'encodings.iso8859_10', 'encodings.utf_32_le', 'encodings.iso2022_jp', 'encodings.cp856', 'encodings.ascii', 'encodings.gb18030', 'encodings.cp864', 'encodings.iso8859_9', 'encodings.latin_1', 'encodings.utf_16', 'encodings.cp037', 'encodings.cp1253', 'encodings.kz1048', 'encodings.mac_arabic', 'encodings.cp1006', 'encodings.mac_latin2', 'encodings.punycode', 'encodings.euc_kr', 'encodings.unicode_internal', 'encodings.cp775', 'encodings.big5hkscs', 'encodings.cp862', 'encodings.iso8859_13', 'encodings.charmap', 'encodings.cp737', 'encodings.cp855', 'encodings.cp861', 'encodings.shift_jis'}
9265 DEBUG: Adding python files to base_library.zip
9343 DEBUG: Hidden import: codecs
9343 DEBUG: Hidden import 'codecs' already found
9343 INFO: running Analysis Analysis-00.toc
9343 DEBUG: Analyzing c:\program files\python36\python.exe
9354 DEBUG: Dependent assemblies of c:\program files\python36\python.exe:
9356 DEBUG: *_Microsoft.Windows.Common-Controls_6595b64144ccf1df_6.0.0.0_none
9356 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by c:\program files\python36\python.exe
9356 DEBUG: Skipping assembly *_Microsoft.Windows.Common-Controls_6595b64144ccf1df_6.0.0.0_none
9376 DEBUG: Adding VCRUNTIME140.dll dependency of python.exe from c:\program files\python36\VCRUNTIME140.dll
9405 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\program files\python36\python.exe
9441 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of c:\program files\python36\python.exe
9441 DEBUG: Adding python36.dll dependency of python.exe from c:\program files\python36\python36.dll
9474 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of c:\program files\python36\python.exe
9482 DEBUG: Skipping KERNEL32.dll dependency of python.exe
9515 WARNING: lib not found: api-ms-win-crt-math-l1-1-0.dll dependency of c:\program files\python36\python.exe
9545 WARNING: lib not found: api-ms-win-crt-locale-l1-1-0.dll dependency of c:\program files\python36\python.exe
9545 DEBUG: Analyzing c:\program files\python36\VCRUNTIME140.dll
9576 WARNING: lib not found: api-ms-win-crt-convert-l1-1-0.dll dependency of c:\program files\python36\VCRUNTIME140.dll
9622 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\program files\python36\VCRUNTIME140.dll
9685 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of c:\program files\python36\VCRUNTIME140.dll
9704 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of c:\program files\python36\VCRUNTIME140.dll
9720 DEBUG: Skipping KERNEL32.dll dependency of VCRUNTIME140.dll
9763 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of c:\program files\python36\VCRUNTIME140.dll
9763 DEBUG: Analyzing c:\program files\python36\python36.dll
9763 DEBUG: Dependent assemblies of c:\program files\python36\python36.dll:
9763 DEBUG: *_Microsoft.Windows.Common-Controls_6595b64144ccf1df_6.0.0.0_none
9763 DEBUG: Skipping assembly *_Microsoft.Windows.Common-Controls_6595b64144ccf1df_6.0.0.0_none
9879 WARNING: lib not found: api-ms-win-crt-convert-l1-1-0.dll dependency of c:\program files\python36\python36.dll
9888 DEBUG: Skipping ADVAPI32.dll dependency of python36.dll
9935 WARNING: lib not found: api-ms-win-crt-math-l1-1-0.dll dependency of c:\program files\python36\python36.dll
9935 DEBUG: Skipping SHLWAPI.dll dependency of python36.dll
10004 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\program files\python36\python36.dll
10046 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of c:\program files\python36\python36.dll
10107 WARNING: lib not found: api-ms-win-crt-environment-l1-1-0.dll dependency of c:\program files\python36\python36.dll
10170 WARNING: lib not found: api-ms-win-crt-process-l1-1-0.dll dependency of c:\program files\python36\python36.dll
10215 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of c:\program files\python36\python36.dll
10248 WARNING: lib not found: api-ms-win-crt-conio-l1-1-0.dll dependency of c:\program files\python36\python36.dll
10341 WARNING: lib not found: api-ms-win-crt-time-l1-1-0.dll dependency of c:\program files\python36\python36.dll
10372 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of c:\program files\python36\python36.dll
10451 WARNING: lib not found: api-ms-win-crt-filesystem-l1-1-0.dll dependency of c:\program files\python36\python36.dll
10451 DEBUG: Skipping KERNEL32.dll dependency of python36.dll
10483 DEBUG: Skipping VERSION.dll dependency of python36.dll
10513 WARNING: lib not found: api-ms-win-crt-locale-l1-1-0.dll dependency of c:\program files\python36\python36.dll
10592 DEBUG: Skipping WS2_32.dll dependency of python36.dll
10592 INFO: Caching module hooks...
10622 INFO: Analyzing C:\Users\jaime\Downloads\A\src\main\python\main.py
20546 INFO: Processing pre-find module path hook   distutils

**Here starts the error:** 

Traceback (most recent call last):
  File "C:\Program Files\Python36\Scripts\pyinstaller-script.py", line 11, in <module>
	load_entry_point('PyInstaller==3.4', 'console_scripts', 'pyinstaller')()
  File "c:\program files\python36\lib\site-packages\PyInstaller\__main__.py", line 111, in run
	run_build(pyi_config, spec_file, **vars(args))
  File "c:\program files\python36\lib\site-packages\PyInstaller\__main__.py", line 63, in run_build
	PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\program files\python36\lib\site-packages\PyInstaller\building\build_main.py", line 838, in main
	build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\program files\python36\lib\site-packages\PyInstaller\building\build_main.py", line 784, in build
	exec(text, spec_namespace)
  File "<string>", line 17, in <module>
  File "c:\program files\python36\lib\site-packages\PyInstaller\building\build_main.py", line 241, in __init__
	self.__postinit__()
  File "c:\program files\python36\lib\site-packages\PyInstaller\building\datastruct.py", line 158, in __postinit__
	self.assemble()
  File "c:\program files\python36\lib\site-packages\PyInstaller\building\build_main.py", line 443, in assemble
	priority_scripts.append(self.graph.run_script(script))
  File "c:\program files\python36\lib\site-packages\PyInstaller\depend\analysis.py", line 201, in run_script
	self._top_script_node = super(PyiModuleGraph, self).run_script(pathname)
  File "c:\program files\python36\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1348, in run_script
	self._scan_code(m, co, co_ast)
  File "c:\program files\python36\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2544, in _scan_code
	self._process_imports(module)
  File "c:\program files\python36\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2743, in _process_imports
	target_module = self._safe_import_hook(*import_info, **kwargs)[0]
  File "c:\program files\python36\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2221, in _safe_import_hook
	target_attr_names=None, level=level, edge_attr=edge_attr)
  File "c:\program files\python36\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1421, in import_hook
	source_package, target_module_partname, level)
  File "c:\program files\python36\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1573, in _find_head_package
	target_module_headname, target_package_name, source_package)
  File "c:\program files\python36\lib\site-packages\PyInstaller\depend\analysis.py", line 271, in _safe_import_module
	module_basename, module_name, parent_package)
  File "c:\program files\python36\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1990, in _safe_import_module
	module_name, file_handle, pathname, metadata)
  File "c:\program files\python36\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2028, in _load_module
	m = self._load_package(fqname, pathname, packagepath)
  File "c:\program files\python36\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2813, in _load_package
	self._load_module(fqname, fp, buf, stuff)
  File "c:\program files\python36\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2082, in _load_module
	self._scan_code(m, co, co_ast)
  File "c:\program files\python36\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2544, in _scan_code
	self._process_imports(module)
  File "c:\program files\python36\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2743, in _process_imports
	target_module = self._safe_import_hook(*import_info, **kwargs)[0]
  File "c:\program files\python36\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2221, in _safe_import_hook
	target_attr_names=None, level=level, edge_attr=edge_attr)
  File "c:\program files\python36\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1421, in import_hook
	source_package, target_module_partname, level)
  File "c:\program files\python36\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1573, in _find_head_package
	target_module_headname, target_package_name, source_package)
  File "c:\program files\python36\lib\site-packages\PyInstaller\depend\analysis.py", line 271, in _safe_import_module
	module_basename, module_name, parent_package)
  File "c:\program files\python36\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1990, in _safe_import_module

**It starts again
Repeated stuff**

  File "c:\program files\python36\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2028, in _load_module
	m = self._load_package(fqname, pathname, packagepath)
  File "c:\program files\python36\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2786, in _load_package
	ns_pkgpath = _namespace_package_path(fqname, pkgpath or [], self.path)
  File "c:\program files\python36\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 147, in _namespace_package_path
	working_set = pkg_resources.WorkingSet(path)
  File "c:\program files\python36\lib\site-packages\pkg_resources\__init__.py", line 565, in __init__
	self.add_entry(entry)
  File "c:\program files\python36\lib\site-packages\pkg_resources\__init__.py", line 621, in add_entry
	for dist in find_distributions(entry, True):
  File "c:\program files\python36\lib\site-packages\pkg_resources\__init__.py", line 1964, in find_on_path
	path_item_entries = _by_version_descending(filtered)
  File "c:\program files\python36\lib\site-packages\pkg_resources\__init__.py", line 1937, in _by_version_descending
	return sorted(names, key=_by_version, reverse=True)
  File "c:\program files\python36\lib\site-packages\pkg_resources\__init__.py", line 1935, in _by_version
	return [packaging.version.parse(part) for part in parts]
  File "c:\program files\python36\lib\site-packages\pkg_resources\__init__.py", line 1935, in <listcomp>
	return [packaging.version.parse(part) for part in parts]
  File "c:\program files\python36\lib\site-packages\pkg_resources\_vendor\packaging\version.py", line 31, in parse
	return Version(version)
RecursionError: maximum recursion depth exceeded while calling a Python object
Traceback (most recent call last):
  File "C:\Program Files\Python36\Scripts\fbs-script.py", line 11, in <module>
	load_entry_point('fbs==0.8.6', 'console_scripts', 'fbs')()
  File "c:\program files\python36\lib\site-packages\fbs\__main__.py", line 17, in _main
	fbs.cmdline.main()
  File "c:\program files\python36\lib\site-packages\fbs\cmdline.py", line 32, in main
	fn(*args)
  File "c:\program files\python36\lib\site-packages\fbs\builtin_commands\__init__.py", line 120, in freeze
	freeze_windows(debug=debug)
  File "c:\program files\python36\lib\site-packages\fbs\freeze\windows.py", line 18, in freeze_windows
	run_pyinstaller(args, debug)
  File "c:\program files\python36\lib\site-packages\fbs\freeze\__init__.py", line 47, in run_pyinstaller
	run(args, check=True)
  File "c:\program files\python36\lib\subprocess.py", line 438, in run
	output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['pyinstaller', '--name', 'Dibujo tÃ©cnico', '--noupx', '--log-level', 'DEBUG', '--noconfirm', '--icon', 'C:\\Users\\jaime\\Downloads\\A\\src\\main\\icons\\Icon.ico', '--distpath', 'C:\\Users\\jaime\\Downloads\\A\\target', '--specpath', 'C:\\Users\\jaime\\Downloads\\A\\target\\PyInstaller', '--workpath', 'C:\\Users\\jaime\\Downloads\\A\\target\\PyInstaller', '--additional-hooks-dir', 'c:\\program files\\python36\\lib\\site-packages\\fbs\\freeze\\hooks', '--debug', 'all', '--runtime-hook', 'C:\\Users\\jaime\\Downloads\\A\\target\\PyInstaller\\fbs_pyinstaller_hook.py', 'C:\\Users\\jaime\\Downloads\\A\\src\\main\\python\\main.py']' returned non-zero exit status 1.
```

 * It is caused by any app **with a import sympy statement, very important**

**Comment by Jaime02** [comment]
I think this issue is related to https://github.com/pyinstaller/pyinstaller/issues/4406

**Comment by mherrmann** [comment]
This is a PyInstaller issue and should be fixed there.

**Comment by Jaime02** [comment]
Can you please check this? https://github.com/pyinstaller/pyinstaller/issues/4406#issuecomment-590849493
Pyinstaller worked but fbs don't.

**Comment by mherrmann** [comment]
> Can you please check this?

Can you please pay me to spend my time helping you?

**Comment by Jaime02** [comment]
I can not pay you, I am a student which is creating a free app for other students. The error may be caused by fbs because Pyinstaller is able to freeze the app but fbs is not.

**Comment by mherrmann** [comment]
And I cannot spend my time helping you for free. I think it's pretty audacious that you would even consider this. Go freeload somewhere else.

**Comment by Jaime02** [comment]
I only wanted to report that bug because many people have this kind of problems and nobody does nothing. I know you would like to get a reward for your work, but I can not pay you in order to fix a bug in your program (or pyinstaller, i do not know what fails). You are getting profit from using Pyinstaller, which is developed by people who loves coding and contribute as much as they can without expecting income. I really hope someone will fix this error.
Despite you have being quite rude to me, thank you for your time & have a good one.

**Comment by garid3000** [comment]
GUYS, I found a solution for this:
This is caused at the file: 
"**_File "C:\Program Files\Python36\Scripts\pyinstaller-script.py", line 11, in <module>"_**
So I added `sys.setrecursionlimit(4000)` to this **Scripts\pyinstaller-script.py** file.

Like this:

`#!c:\users\garid\appdata\local\programs\python\python36\python.exe
# EASY-INSTALL-ENTRY-SCRIPT: 'PyInstaller==3.4','console_scripts','pyinstaller'
__requires__ = 'PyInstaller==3.4'
import re
import sys
sys.setrecursionlimit(4000)                                          #this is added
print("garid added: sys.setrecursionlimit(4000)")        #this is added
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('PyInstaller==3.4', 'console_scripts', 'pyinstaller')()
    )
`
