### ISSUE TITLE
fbs freeze is failing

### ISSUE THREAD

**Issue by raidu4u** [mherrmann/fbs#243]
Issue occurred when running fbs freeze.

 * Ubuntu 18.04
 * Python 3.6
 * fbs 1.0.3
 * PyInstaller==4.5
 * PySide2==5.15.2
 * Able to run application using **fbs run**, but unable to run **fbs freeze**
  ```
(env_ps5) ➜  ps5_client git:(qml_exp) fbs freeze --debug
Traceback (most recent call last):
  File "/home/rayudu/projects/pietrack/env_ps5/bin/fbs", line 8, in <module>
    sys.exit(_main())
  File "/home/rayudu/projects/pietrack/env_ps5/lib/python3.6/site-packages/fbs/__main__.py", line 17, in _main
    fbs.cmdline.main()
  File "/home/rayudu/projects/pietrack/env_ps5/lib/python3.6/site-packages/fbs/cmdline.py", line 32, in main
    fn(*args)
  File "/home/rayudu/projects/pietrack/env_ps5/lib/python3.6/site-packages/fbs/builtin_commands/__init__.py", line 129, in freeze
    freeze_ubuntu(debug=debug)
  File "/home/rayudu/projects/pietrack/env_ps5/lib/python3.6/site-packages/fbs/freeze/ubuntu.py", line 4, in freeze_ubuntu
    freeze_linux(debug)
  File "/home/rayudu/projects/pietrack/env_ps5/lib/python3.6/site-packages/fbs/freeze/linux.py", line 8, in freeze_linux
    run_pyinstaller(debug=debug)
  File "/home/rayudu/projects/pietrack/env_ps5/lib/python3.6/site-packages/fbs/freeze/__init__.py", line 47, in run_pyinstaller
    cp = run(args, capture_output=True, text=True)
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'capture_output'
```

**Comment by mherrmann** [comment]
Can you try with Python 3.7?

**Comment by raidu4u** [comment]
It worked, thanks for quick response.
