### ISSUE TITLE
Releasing Mac Version of application SSL error

### ISSUE THREAD

**Issue by brian316** [mherrmann/fbs#254]
I get an error when using the `fbs release <version>` command. I sometimes get this on windows as well, but after several tries, it works. Cant get it to work on macOS.

### Error Message
```
waited 1 seconds for .DS_STORE to be created.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1253, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1299, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1248, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1008, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 948, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1422, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/brian/.local/share/virtualenvs/app-ooniLFkl/bin/fbs", line 8, in <module>
    sys.exit(_main())
  File "/Users/brian/.local/share/virtualenvs/app-ooniLFkl/lib/python3.9/site-packages/fbs/__main__.py", line 17, in _main
    fbs.cmdline.main()
  File "/Users/brian/.local/share/virtualenvs/app-ooniLFkl/lib/python3.9/site-packages/fbs/cmdline.py", line 32, in main
    fn(*args)
  File "/Users/brian/.local/share/virtualenvs/app-ooniLFkl/lib/python3.9/site-packages/fbs/builtin_commands/__init__.py", line 475, in release
    upload()
  File "/Users/brian/.local/share/virtualenvs/app-ooniLFkl/lib/python3.9/site-packages/fbs/builtin_commands/__init__.py", line 365, in upload
    _upload_repo(username, password)
  File "/Users/brian/.local/share/virtualenvs/app-ooniLFkl/lib/python3.9/site-packages/fbs/upload.py", line 10, in _upload_repo
    status, response = _server.post_json('start_upload', {
  File "/Users/brian/.local/share/virtualenvs/app-ooniLFkl/lib/python3.9/site-packages/fbs/_server.py", line 16, in post_json
    with urlopen(request, data_bytes) as response:
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 1349, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)>
(app) ---------------------------
~/personal-projects/dca-app/app(main*) » openssl   1 ↵ brian@Brians-MacBook-Pro
OpenSSL> exit
(app) ---------------------------

```

 * macOS BigSur
 * python3.9
 * fbs pro 1.0.6
 * PyInstaller 4.5.1
 * Psyide6

**Comment by brian316** [comment]
I solved the issue. It has to do with macOS not providing openssl headers.

Im Using Python3.9 which should include its own version of openssl so im not sure why its not working...

### ISSUE
You get the error `SSL: CERTIFICATE_VERIFY_FAILED`

### FIX
I ran the following command in my terminal *(Adjust to your path/ python version)*
`/Applications/Python\ 3.9/Install\ Certificates.command `

[stackoverflow link for reference](https://stackoverflow.com/questions/27835619/urllib-and-ssl-certificate-verify-failed-error.)

**Comment by brian316** [comment]
Maybe I need to open a separate thread for this please let me know 
but now that I release the app it is corrupted when I download and install. The created installer using `fbs installer` installs and works fine but when I upload and download to test it gets installed but when I try to open the app it gives an error.

![image](https://user-images.githubusercontent.com/3878246/136503359-7b2abd42-f8aa-4296-85f4-1807423bbefe.png)

**Comment by mherrmann** [comment]
Maybe this has to do with the recent expiration of LetsEncrypt's root certificate. I renewed the SSL certificate of build-system.fman.io. Are you still getting the error?

**Comment by Per-Bronson** [comment]
I have the same problem. Fine when I use "fbs installer", but damaged dmg.-file when "fbs upload" and downloaded.

**Comment by mherrmann** [comment]
The above error message was not about a damaged .dmg file.
