### ISSUE TITLE
AttributeError: 'version_info' object has no attribute '__version__'

### ISSUE THREAD

**Issue by amarnathreddy0201** [mherrmann/fbs#272]
Hi Sir,

I am using python 3.6.0 when i run the code fbs run it giving below error.

how can i fix this error ,is any dependency of any module ?

```Traceback (most recent call last):
  File "C:\Development\qa-cal\sysqa\src\main\python\scripts\run_gui_server.py", line 10, in <module>
    from gui.gui_pyqt_client import GuiPyqt
  File "C:\Development\qa-cal\sysqa\src\main\python\gui\gui_pyqt_client.py", line 45, in <module>
    from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg
  File "c:\development\py-3.6\lib\site-packages\matplotlib\__init__.py", line 107, in <module>
    from . import cbook, rcsetup
  File "c:\development\py-3.6\lib\site-packages\matplotlib\rcsetup.py", line 28, in <module>
    from matplotlib.fontconfig_pattern import parse_fontconfig_pattern
  File "c:\development\py-3.6\lib\site-packages\matplotlib\fontconfig_pattern.py", line 15, in <module>
    from pyparsing import (Literal, ZeroOrMore, Optional, Regex, StringEnd,
  File "c:\development\py-3.6\lib\site-packages\pyparsing\__init__.py", line 130, in <module>
    __version__ = __version_info__.__version__
AttributeError: 'version_info' object has no attribute '__version__'```

If you have read all of the above, and only then, please delete this text and let me know the following:

 * Your operating system(s)-windows10
 * Your Python version-3.6.0
 * Your fbs version-1.1.2
 * Your PyInstaller version-3.4
 * Your PyQt / PySide version-5.9.2
 


Thanks,
ANR S

**Comment by mherrmann** [comment]
There's no fbs in this stack trace. So I don't think this is caused by fbs.

**Comment by amarnathreddy0201** [comment]
Thanks for response sir.

I got the error because of pyparsing.

https://stackoverflow.com/questions/69964466/unknown-version-in-python-library-pyparsing

**Comment by amarnathreddy0201** [comment]
Thanks for helping
