### ISSUE TITLE
Incorrect link to `fpm` install page

### ISSUE THREAD

**Issue by bicarlsen** [mherrmann/fbs#277]
When running `fbs installer` I get the error 

```bash
Traceback (most recent call last):
  File "/home/brian/Dropbox/Documents/www/thot/src/desktop-0.9.x/app/.venv-ubuntu22/bin/fbs", line 11, in <module>
    load_entry_point('fbs==1.1.2', 'console_scripts', 'fbs')()
  File "/home/brian/Dropbox/Documents/www/thot/src/desktop-0.9.x/app/.venv-ubuntu22/lib/python3.6/site-packages/fbs/__main__.py", line 17, in _main
    fbs.cmdline.main()
  File "/home/brian/Dropbox/Documents/www/thot/src/desktop-0.9.x/app/.venv-ubuntu22/lib/python3.6/site-packages/fbs/cmdline.py", line 32, in main
    fn(*args)
  File "/home/brian/Dropbox/Documents/www/thot/src/desktop-0.9.x/app/.venv-ubuntu22/lib/python3.6/site-packages/fbs/builtin_commands/__init__.py", line 196, in installer
    create_installer_ubuntu()
  File "/home/brian/Dropbox/Documents/www/thot/src/desktop-0.9.x/app/.venv-ubuntu22/lib/python3.6/site-packages/fbs/installer/ubuntu.py", line 5, in create_installer_ubuntu
    run_fpm('deb')
  File "/home/brian/Dropbox/Documents/www/thot/src/desktop-0.9.x/app/.venv-ubuntu22/lib/python3.6/site-packages/fbs/installer/linux.py", line 69, in run_fpm
    ) from None
FileNotFoundError: fbs could not find executable 'fpm'. Please install fpm using the instructions at https://fpm.readthedocs.io/en/latest/installing.html.
```

However, the link to the `fpm` installation instructions in the last line is dead. The current working link is [https://fpm.readthedocs.io/en/latest/installation.html](https://fpm.readthedocs.io/en/latest/installation.html) (`installing.html` -> `installation.html`).

**Comment by mherrmann** [comment]
Fixed by @meramsey in [1.1.3](https://github.com/mherrmann/fbs/releases/tag/v1.1.3).
