### ISSUE TITLE
freeze on macOS Monterey gives warnings

### ISSUE THREAD

**Issue by mherrmann** [mherrmann/fbs#282]
Originally asked by @proftc [here](https://github.com/fman-users/fman/issues/862).

When running fbs freeze on Monterey I get pages of missing dependencies
though it worked perfectly on Mojave

A typical msg is

(venvCD37A) IT036317:FBS_Test terry$ fbs release 1.0.0 5020 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /Users/terry/.pyenv/versions/3.7.7/bin/python3.7)

However the final dmg is created and works? I googled this and it seems that Monterey has now hidden some libraries? Is there a way around this?

**Comment by mherrmann** [comment]
@proftc have you already purchased a license of [fbs Pro](https://build-system.fman.io/pro)?

**Comment by proftc** [comment]
Hi Michael
Yes I have
Terry


¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬
Professor Terence Cosgrove                  TEL     +44 (0) 1275 845230
School of Chemistry                                TEL     +1  239 304 5982
Cantock's Close                                       ***@***.***
Bristol BS8 1TS UK
http://www.chm.bris.ac.uk/pt/polymer/pig_home.htm
¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬

From: Michael Herrmann ***@***.***>
Reply to: mherrmann/fbs ***@***.***>
Date: Monday, 25 July 2022 at 08:42
To: mherrmann/fbs ***@***.***>
Cc: Terence Cosgrove ***@***.***>, Mention ***@***.***>
Subject: Re: [mherrmann/fbs] freeze on macOS Monterey gives warnings (Issue #282)


@proftc<https://github.com/proftc> have you already purchased a license of fbs Pro<https://build-system.fman.io/pro>?

**Comment by mherrmann** [comment]
@proftc this looks like https://github.com/pyinstaller/pyinstaller/issues/5107 to me. Does the problem go away when you update to a newer version of PyInstaller?

**Comment by proftc** [comment]
I have PyInstaller    3.4 in my virtual environment and I'm using Python 3.7.7 but I was concerned up updating either of these
as the error ( as in that link you sen which I had already seen) seems more fundamental. Can you recommend which versions I should try? Thanks

**Comment by proftc** [comment]
I installed pyinstaller 5.5 and now FBS freeze works OK without the error messages and the app that is created runs. However when I~ try to use FBS  installer I get this error
hdiutil: create failed - Resource busy

**Comment by mherrmann** [comment]
I'm often able to resolved `hdiutil: create failed` by rebooting.

**Comment by proftc** [comment]
Hi Michael
I did try that and it ssemed to producw an installer icon which gthen allowed me to
Onstall the program the normal way but I got these messages

hdiutil: couldn't unmount "disk2" - Resource busy
Traceback (most recent call last):
  File "/Users/terry/.pyenv/versions/New37/bin/fbs", line 11, in <module>
    load_entry_point('fbs==1.0.0', 'console_scripts', 'fbs')()
  File "/Users/terry/.pyenv/versions/3.7.7/envs/New37/lib/python3.7/site-packages/fbs/__main__.py", line 17, in _main
    fbs.cmdline.main()
  File "/Users/terry/.pyenv/versions/3.7.7/envs/New37/lib/python3.7/site-packages/fbs/cmdline.py", line 32, in main
    fn(*args)
  File "/Users/terry/.pyenv/versions/3.7.7/envs/New37/lib/python3.7/site-packages/fbs/builtin_commands/__init__.py", line 183, in installer
    create_installer_mac()
  File "/Users/terry/.pyenv/versions/3.7.7/envs/New37/lib/python3.7/site-packages/fbs/installer/mac/__init__.py", line 29, in create_installer_mac
    check_call(pdata, stdout=DEVNULL)
  File "/Users/terry/.pyenv/versions/3.7.7/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/terry/.pyenv/versions/3.7.7/envs/New37/lib/python3.7/site-packages/fbs/installer/mac/create-dmg/create-dmg', '--no-internet-enable', '--volname', 'Relax', '--app-drop-link', '170', '10', '--icon', 'Relax.app', '0', '10', '/Users/terry/Python/FBS_Examples/FBS_Relax/target/Relax.dmg', '/Users/terry/Python/FBS_Examples/FBS_Relax/target/Relax.app']' returned non-zero exit status 16.

I closed the installer icon and then I had the same problem as before?
Is this something peculiar in Monterey  as  I often  get a message something like  ‘please give  folder access to this program ‘ with for example Xcode when it is writing a file to disk. Does Pyinstaller need some special permissions set?
Thanks
Terry


¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬
Professor Terence Cosgrove                  TEL     +44 (0) 1275 845230
School of Chemistry                                TEL     +1  239 304 5982
Cantock's Close                                       ***@***.***
Bristol BS8 1TS UK
http://www.chm.bris.ac.uk/pt/polymer/pig_home.htm
¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬

From: Michael Herrmann ***@***.***>
Reply to: mherrmann/fbs ***@***.***>
Date: Sunday, 11 September 2022 at 14:06
To: mherrmann/fbs ***@***.***>
Cc: Terence Cosgrove ***@***.***>, Mention ***@***.***>
Subject: Re: [mherrmann/fbs] freeze on macOS Monterey gives warnings (Issue #282)


I'm often able to resolve hdiutil: create failed by rebooting.
