### ISSUE TITLE
FBS cannot find makensis even though it is installed

### ISSUE THREAD

**Issue by adwaye** [mherrmann/fbs#293]
Running fbs installer on my application gives the following error:

 * Your operating system(s): Microsoft Windows 10 Enterprise, 10.0.190044 build 19044
 * Your Python version: 3.6
 * Your fbs version: 1.1.9
 * Your PyInstaller version: 3.4
 * Your PyQt / PySide version: PyQt5==5.15.6
 

 ```
(pyqt5) C:\Users\goku\PycharmProjects\fbsProject>fbs startproject
(pyqt5) C:\Users\goku\PycharmProjects\fbsProject>fbs freeze
(pyqt5) C:\Users\goku\PycharmProjects\fbsProject>fbs installer
 ```
```
   Traceback (most recent call last):
    File "c:\Users\amr62\Documents\python_environments\pyqt5\Scripts\fbs-script.py", line 33, in <module>
      sys.exit(load_entry_point('fbs==1.1.9', 'console_scripts', 'fbs')())
    File "c:\users\amr62\documents\python_environments\pyqt5\lib\site-packages\fbs\__main__.py", line 17, in _main
      fbs.cmdline.main()
    File "c:\users\amr62\documents\python_environments\pyqt5\lib\site-packages\fbs\cmdline.py", line 32, in main
      fn(*args)
    File "c:\users\amr62\documents\python_environments\pyqt5\lib\site-packages\fbs\builtin_commands\__init__.py", line 188, in insta
  ller
      create_installer_windows()
    File "c:\users\amr62\documents\python_environments\pyqt5\lib\site-packages\fbs\installer\windows.py", line 16, in create_install
  er_windows
      ) from None
  FileNotFoundError: fbs could not find executable 'makensis'. Please install NSIS and add its installation directory to your PATH e
  nvironment variable.
```

```
(pyqt5) C:\Users\goku\PycharmProjects\fbsProject>echo %NSIS%
C:\Program Files (x86)\NSIS
(pyqt5) C:\Users\goku\PycharmProjects\fbsProject>echo %makensis%
C:\Program Files (x86)\NSIS\makensis.exe
```

Would be grateful for any help on this.

**Comment by meramsey** [comment]
need to add it to your path env like you would add the codesigning libs. see example for that here
https://github.com/mherrmann/fbs-tutorial/pull/47/files#diff-04c6e90faac2675aa89e2176d2eec7d8

**Comment by gabrieljreed** [comment]
I know this is late, but did you [add it to the windows PATH](https://www.architectryan.com/2018/03/17/add-to-the-path-on-windows-10/)? After you've done that, you may need to restart your terminal and/or machine (depending on if you added to User path or System path).

**Comment by meramsey** [comment]
Yeah would be user user env path and a reboot should do it.  I think if you run powershell `refreshenv` it might work without a reboot but a reboot is probably the safest way to ensure it.

It is very similiar to signtool snippet i put up awhile back
https://github.com/mherrmann/fbs-tutorial/pull/47/files#diff-04c6e90faac2675aa89e2176d2eec7d8

**Comment by Ban2Me** [comment]
Under Windows, in your terminal use: set PATH=%PATH%;C:\Program Files (x86)\NSIS\. This should fix your issue
