### ISSUE TITLE
fbs pro experiencing problems with PySide2 (`no module named 'inspect'`)

### ISSUE THREAD

**Issue by gabrieljreed** [mherrmann/fbs#298]
Hi, I've been using/loving the free version of fbs, so I decided to upgrade to Pro. However, I've been running into the following issue in both Python 3.7 and 3.9 while trying to use PySide2.

Windows 10
Python 3.7 and 3.9
FBS 1.2.1
PyInstaller 5.12.0
PySide2 5.15.2.1

<details open><summary>Error</summary>

```
Problem importing shibokensupport:
No module named 'inspect'
sys.path:
  C:\Users\Biggs\AppData\Local\Temp\embedded.w6uaknd3.zip
  C:\Users\Biggs\Desktop\fbsProTest\target\MyApp\base_library.zip
  C:\Users\Biggs\Desktop\fbsProTest\target\MyApp\lib-dynload
  C:\Users\Biggs\Desktop\fbsProTest\target\MyApp
Fatal Python error: could not initialize part 2

Current thread 0x0000251c (most recent call first):
  File "shiboken2\__init__.py", line 30 in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385 in exec_module
  File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 983 in _find_and_load
  File "PySide2\__init__.py", line 58 in _setupQtDirectories
  File "PySide2\__init__.py", line 107 in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385 in exec_module
  File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 983 in _find_and_load
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 953 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 983 in _find_and_load
  File "fbs_runtime\application_context\PySide2.py", line 2 in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385 in exec_module
  File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 983 in _find_and_load
  File "main.py", line 1 in <module>
Traceback (most recent call last):
  File "(builtin)", line 93, in ensure_shibokensupport
  File "(builtin)", line 133, in bootstrap
  File "C:\Users\Biggs\AppData\Local\Temp\embedded.w6uaknd3.zip\shibokensupport\signature\loader.py", line 158, in <module>
    import inspect
ModuleNotFoundError: No module named 'inspect'
Traceback (most recent call last):
  File "(builtin)", line 93, in ensure_shibokensupport
  File "(builtin)", line 133, in bootstrap
  File "C:\Users\Biggs\AppData\Local\Temp\embedded.w6uaknd3.zip\shibokensupport\signature\loader.py", line 158, in <module>
ModuleNotFoundError: No module named 'inspect'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "(builtin)", line 133, in bootstrap
  File "contextlib.py", line 130, in __exit__
  File "(builtin)", line 102, in ensure_shibokensupport
SystemExit: -1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "(builtin)", line 147, in bootstrap
UnboundLocalError: local variable 'loader' referenced before assignment

```
</details>

This is the output I get from creating a new project from scratch and leaving everything as default. The problem does not appear to occur when I use PySide6 or PyQt5 (and potentially other versions of PyQt, but I haven't had time to test yet).

To set up the project, I created a blank directory, copied in the fbs-pro tar file, created a new venv in the same folder, activated the venv, then used pip to install fbs from the tar file along with PySide2. Then I ran `fbs startproject`, left all settings as default, and ran `fbs freeze`. 

Is it possible that PySide2 is no longer supported? This is what our team has been using, so we could port our code to another version of Qt but we'd prefer not to. I tried looking on the troubleshooting page to find the supported versions of PyQt/PySide but I didn't see them? 

Again, if it's just a problem of not being able to use PySide2, that's definitely on me! I tried to see if it's still supported but I'm not sure where to look. (I didn't have any problems with PySide2 while I was using the free version of fbs.)

**Comment by gabrieljreed** [comment]
I think I've found the solution, which is to simply include `inspect` in the `"hidden_imports"` section of `src/build/settings/base.json`. This wasn't working for me earlier, but I have to assume that was simply user error. Not 100% sure why this needs to be done, but it seems to be a working solution. Sorry for the trouble.

**Comment by mherrmann** [comment]
I'm happy to hear you got it to work. Thank you also for documenting your solution here. I don't have time to investigate for the Hobbyist license; Maybe it is because the new PyInstaller version no longer properly supports the old PySide2.
