### ISSUE TITLE
IndexError when creating fbs project structure

### ISSUE THREAD

**Issue by jonasstoetzel** [mherrmann/fbs#41]
Hi!
I'm on Windows 7 using Python 3.5.2. When I follow the tutorial's instructions to create the fbs project structure and rerun my app, I get

    Traceback (most recent call last):
    File "main.py", line 31, in <module>
      File "C:\Users\test\testumgebung\venv\lib\site-packages\fbs_runtime\application_context.py", line 38, in __init__
        self._resource_locator = self._create_resource_locator()
      File "C:\Users\test\testumgebung\venv\lib\site-packages\fbs_runtime\application_context.py", line 58, in _create_resource_locator
         return _DevelopmentResourceLocator(self.__class__)
      File "C:\Users\test\testumgebung\venv\lib\site-packages\fbs_runtime\application_context.py", line 115, in __init__
        project_dir = self._get_project_base_dir(appctxt_cls)
      File "C:\Users\test\testumgebung\venv\lib\site-packages\fbs_runtime\application_context.py", line 127, in _get_project_base_dir
        parent_names = [p.parents[2].name, p.parents[1].name, p.parent.name]
      File "C:\Users\test\AppData\Local\Programs\Python\Python35-32\lib\pathlib.py", line 594, in __getitem__
        raise IndexError(idx)
    IndexError: 2

my ```main.py```:

    #! /usr/bin/env python
    # encoding: utf-8

    import logging
    import sys

    from fbs_runtime.application_context import ApplicationContext
    import pruefung

    class AppContext(ApplicationContext):

        def run(self):
            pr = pruefung.PruefungApp()
            return self.app.exec_()

    if __name__ == '__main__':
        appctxt = AppContext()
        exit_code = appctxt.run()
        sys.exit(exit_code)

```pip freeze```:

    altgraph==0.16.1
    certifi==2018.10.15
    chardet==3.0.4
    fbs==0.3.6
    future==0.17.1
    idna==2.7
    influxdb==5.2.0
    iso8601==0.1.12
    macholib==1.11
    numpy==1.15.4
    pandas==0.23.4
    pefile==2018.8.8
    PyInstaller==3.3.1
    pypiwin32==223
    PyQt5==5.9.2
    pyserial==3.4
    python-dateutil==2.7.5
    pytz==2018.7
    pywin32==224
    PyYAML==3.13
    requests==2.20.0
    sip==4.19.8
    six==1.11.0
    urllib3==1.24.1
    xlrd==1.1.0

Did you encounter this issue before? The error persists when I run ```python -m fbs startproject```. When I run ```python -m fbs run``` I get an empty window.

**Comment by mherrmann** [comment]
Sorry, when you do get this error? When you do `python -m fbs` run?

**Comment by jonasstoetzel** [comment]
No, when I execute ```python main.py``` to check if everything works.

**Comment by jonasstoetzel** [comment]
No change, this starts the empty window.
Just to be clear: the app is still supposed to run after I introduce the fbs project structure (5. in https://build-system.fman.io/pyqt-exe-creation/) and before I ```startprojet```and ```run```, right?
Also, i meant ```python main.py``` in the project root directory

**Comment by mherrmann** [comment]
If it opens the empty window then I suspect that you have two (different) files called `main.py`. Could that be?

**Comment by mherrmann** [comment]
Or, I mean, does `pr = pruefung.PruefungApp()` actually call `.show()` on a widget?

**Comment by jonasstoetzel** [comment]
> If it opens the empty window then I suspect that you have two (different) files called main.py. Could that be?

I dont understand. I got a main.py in the root directory and another one in src\main\python. And yes, the latter one does not have the ```pr = pruefung.PruefungApp()```

> Or, I mean, does pr = pruefung.PruefungApp() actually call .show() on a widget?

Yes, it does.

**Comment by mherrmann** [comment]
You should only have one `main.py`. It should be in `src/main/python`.

**Comment by jonasstoetzel** [comment]
Yes, I overlooked the tutorial paragraph to move all python source files into src\main\python. Sorry for that. After I did this, the app started sucessfully. Freezing it is still an issue, but I'll report tomorrow.

**Comment by mherrmann** [comment]
Okay :-)

**Comment by jonasstoetzel** [comment]
Seems that I have a unicode error somewhere.

    Traceback (most recent call last):
      File "C:\Users\test\testumgebung\venv\Scripts\pyinstaller-script.py", line 9, in <module>
        load_entry_point('PyInstaller==3.3.1', 'console_scripts', 'pyinstaller')()
      File "c:\users\test\testumgebung\venv\lib\site-packages\PyInstaller\__main__.py", line 94, in run
        run_build(pyi_config, spec_file, **vars(args))
      File "c:\users\test\testumgebung\venv\lib\site-packages\PyInstaller\__main__.py", line 46, in run_build
        PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
      File "c:\users\test\testumgebung\venv\lib\site-packages\PyInstaller\building\build_main.py", line 791, in main
        build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
      File "c:\users\test\testumgebung\venv\lib\site-packages\PyInstaller\building\build_main.py", line 737, in build
        exec(text, spec_namespace)
      File "<string>", line 16, in <module>
      File "c:\users\test\testumgebung\venv\lib\site-packages\PyInstaller\building\build_main.py", line 213, in __init__
        self.__postinit__()
      File "c:\users\test\testumgebung\venv\lib\site-packages\PyInstaller\building\datastruct.py", line 161, in __postinit__
        self.assemble()
      File "c:\users\test\testumgebung\venv\lib\site-packages\PyInstaller\building\build_main.py", line 415, in assemble
        priority_scripts.append(self.graph.run_script(script))
      File "c:\users\test\testumgebung\venv\lib\site-packages\PyInstaller\depend\analysis.py", line 201, in run_script
        self._top_script_node = super(PyiModuleGraph, self).run_script(pathname)
      File "c:\users\test\testumgebung\venv\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1338, in run_script
        contents = fp.read() + '\n'
      File "C:\Users\test\AppData\Local\Programs\Python\Python35-32\lib\codecs.py", line 321, in decode
        (result, consumed) = self._buffer_decode(data, self.errors, final)
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfc in position 454: invalid start byte
    Traceback (most recent call last):
      File "C:\Users\test\AppData\Local\Programs\Python\Python35-32\lib\runpy.py", line 184, in _run_module_as_main
        "__main__", mod_spec)
      File "C:\Users\test\AppData\Local\Programs\Python\Python35-32\lib\runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "C:\Users\test\testumgebung\venv\lib\site-packages\fbs\__main__.py", line 4, in <module>
        main()
      File "C:\Users\test\testumgebung\venv\lib\site-packages\fbs\cmdline.py", line 26, in main
        args.fn(*fn_args)
      File "C:\Users\test\testumgebung\venv\lib\site-packages\fbs\builtin_commands\__init__.py", line 90, in freeze
        freeze_windows(debug=debug)
      File "C:\Users\test\testumgebung\venv\lib\site-packages\fbs\freeze\windows.py", line 20, in freeze_windows
        run_pyinstaller(pyinstaller_args + extra_pyinstaller_args, debug)
      File "C:\Users\test\testumgebung\venv\lib\site-packages\fbs\freeze\__init__.py", line 31, in run_pyinstaller
        run(args, check=True)
      File "C:\Users\test\AppData\Local\Programs\Python\Python35-32\lib\subprocess.py", line 708, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['pyinstaller', '--name', 'MyApp', '--noupx', '--log-level', 'WARN', '--windowed', '-
    -icon', 'C:\\Users\\test\\testumgebung\\src\\main\\icons\\Icon.ico', '--distpath', 'C:\\Users\\test\\testumge
    bung\\target', '--specpath', 'C:\\Users\\test\\testumgebung\\target\\PyInstaller', '--workpath', 'C:\\Users\\test\\testumgebung\\target\\PyInstaller', 'C:\\Users\\test\\testumgebung\\src\\main\\python\\main.py']' returned non-zero exit status 1

It should be unrelated to this issue though.

**Comment by mherrmann** [comment]
> It should be unrelated to this issue though.

Yeah, I agree. 

I'm getting a little weary of this discussion. I feel like we're doing very haphazard, non-fbs-specific troubleshooting.

Closing this issue for now. If you feel you have found a specific bug in fbs, feel free to open another one. Otherwise, [StackOverflow](https://stackoverflow.com/) is likely a better place for such discussions.
