### ISSUE TITLE
Freeze failed after adding the --debug flag on Windows.

### ISSUE THREAD

**Issue by JeziL** [mherrmann/fbs#72]
I have generated an installer with Appveyor CI system. But when I run the program it shows the `Failed to execute script main` error, so according to the troubleshooting instruction, I added the `--debug` flag:
```
fbs freeze --debug
```
Then the freeze command failed with a `FileNotFoundError`:
```
Traceback (most recent call last):
  File "C:\Python36-x64\Scripts\pyinstaller-script.py", line 11, in <module>
    load_entry_point('PyInstaller==3.4', 'console_scripts', 'pyinstaller')()
  File "c:\python36-x64\lib\site-packages\PyInstaller\__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\python36-x64\lib\site-packages\PyInstaller\__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\python36-x64\lib\site-packages\PyInstaller\building\build_main.py", line 838, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\python36-x64\lib\site-packages\PyInstaller\building\build_main.py", line 784, in build
    exec(text, spec_namespace)
  File "<string>", line 17, in <module>
  File "c:\python36-x64\lib\site-packages\PyInstaller\building\build_main.py", line 241, in __init__
    self.__postinit__()
  File "c:\python36-x64\lib\site-packages\PyInstaller\building\datastruct.py", line 158, in __postinit__
    self.assemble()
  File "c:\python36-x64\lib\site-packages\PyInstaller\building\build_main.py", line 595, in assemble
    for name, path, typecode in compile_py_files(new_toc, CONF['workpath']):
  File "c:\python36-x64\lib\site-packages\PyInstaller\utils\misc.py", line 150, in compile_py_files
    with open(obj_fnm, 'rb') as fh:
FileNotFoundError: [Errno 2] No such file or directory: '-'
Traceback (most recent call last):
  File "C:\Python36-x64\Scripts\fbs-script.py", line 11, in <module>
    load_entry_point('fbs==0.6.6', 'console_scripts', 'fbs')()
  File "c:\python36-x64\lib\site-packages\fbs\__main__.py", line 17, in _main
    fbs.cmdline.main()
  File "c:\python36-x64\lib\site-packages\fbs\cmdline.py", line 32, in main
    fn(*args)
  File "c:\python36-x64\lib\site-packages\fbs\builtin_commands\__init__.py", line 113, in freeze
    freeze_windows(debug=debug)
  File "c:\python36-x64\lib\site-packages\fbs\freeze\windows.py", line 18, in freeze_windows
    run_pyinstaller(args, debug)
  File "c:\python36-x64\lib\site-packages\fbs\freeze\__init__.py", line 43, in run_pyinstaller
    run(args, check=True)
  File "c:\python36-x64\lib\subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['pyinstaller', '--name', 'RadUI', '--noupx', '--log-level', 'DEBUG', '--noconfirm', '--icon', 'C:\\projects\\radui\\src\\main\\icons\\Icon.ico', '--distpath', 'C:\\projects\\radui\\target', '--specpath', 'C:\\projects\\radui\\target\\PyInstaller', '--workpath', 'C:\\projects\\radui\\target\\PyInstaller', 'C:\\projects\\radui\\src\\main\\python\\main.py', '--debug', '--runtime-hook', 'C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\tmpug9nomyf\\fbs_pyinstaller_hook.py']' returned non-zero exit status 1.
```
Any idea why adding a flag can cause a different behavior?

**Comment by mherrmann** [comment]
I don't know, sorry. Does the problem only occur when you build on AppVeyor? Does it also occur for a completely "fresh" project?

    fbs startproject
    fbs freeze --debug

**Comment by JeziL** [comment]
Thanks. I deleted L39~40 and the frozen app still gave me the debug info.

It turns out that my `Failed to execute script main` error is caused by a PyInstaller bug (https://github.com/pyinstaller/pyinstaller/issues/3982), too.

**Comment by mherrmann** [comment]
Great! Thank you for letting me know - and for sharing your solution with @BorisDess in #74 too.

**Comment by Aperion** [comment]
I ran into this same issue, I downgraded to 3.6 and it went away. it also went away in 3.7 if I called `PyInstaller.__main__.run(...)` instead of using `subprocess`.
