### ISSUE TITLE
ModuleNotFoundError: No module named 'win32com'

### ISSUE THREAD

**Issue by BorisDess** [mherrmann/fbs#73]
When adding numpy or pandas packages, I get the follwing messages.
I'm using : 
Python 3.6.8 :: Anaconda, Inc.
PyQt5 5.9.2 and PyInstaller 3.4
fbs 0.6.6
numpy 1.16.0
pandas 0.23.4

```
Traceback (most recent call last):
  File "<string>", line 2, in <module>
ModuleNotFoundError: No module named 'win32com'
Traceback (most recent call last):
  File "<string>", line 2, in <module>
ModuleNotFoundError: No module named 'win32com'
c:\users\boris\appdata\local\continuum\anaconda3\envs\python 3.6\lib\site-packages\sphinx\websupport\__init__.py:25: RemovedInSphinx20Warning: sphinx.websupport module is now provided as sphinxcontrib-websupport. sphinx.websupport will be removed at Sphinx-2.0. Please use the package instead.
  RemovedInSphinx20Warning)
Done. You can now run `target\Test\Test.exe`. If that doesn't work,
see https://build-system.fman.io/troubleshooting.
```

**Comment by BorisDess** [comment]
I fixed the win32com error by installing it using pip install pypiwin32 ; pip install win32com wasn't working.

**Comment by danielmcquillen** [comment]
Thanks for posting @BorisDess
