### ISSUE TITLE
KeyError: 'installer' in Debian 9

### ISSUE THREAD

**Issue by azzamsa** [mherrmann/fbs#89]
```bash
user at machine in build on master <global_py3>
$ fbs freeze
Done. You can now run `target/App/app`. If that doesn't work, see
https://build-system.fman.io/troubleshooting.

user at machine in build on master <global_py3>
$ fbs installer
Traceback (most recent call last):
  File "/home/user/.virtualenvs/global_py3/bin/fbs", line 10, in <module>
    sys.exit(_main())
  File "/home/user/.virtualenvs/global_py3/lib/python3.5/site-packages/fbs/__main__.py", line 17, in _main
    fbs.cmdline.main()
  File "/home/user/.virtualenvs/global_py3/lib/python3.5/site-packages/fbs/cmdline.py", line 32, in main
    fn(*args)
  File "/home/user/.virtualenvs/global_py3/lib/python3.5/site-packages/fbs/builtin_commands/__init__.py", line 146, in installer
    out_file = join('target', SETTINGS['installer'])
KeyError: 'installer'
```

I get above error running `fbs installer` in debian 9. But `freeze` work fine.

I also tried to change `is_ubuntu` according to [this comment](https://github.com/mherrmann/fbs/issues/53#issue-384211359) but no luck.

Thanks a lot for fbs.

**Comment by mherrmann** [comment]
Closing this as "wontfix" because Debian is not officially supported by fbs for now.
