### ISSUE TITLE
raise FbsError('Invalid icon name: ' % icon_path) - Ubuntu

### ISSUE THREAD

**Issue by jerubio** [mherrmann/fbs#91]
Can't complete installer.
I get this error

Traceback (most recent call last):
File "/home/jorge/.virtualenvs/QtOpencv/venv/bin/fbs", line 11, in 
load_entry_point('fbs==0.7.2', 'console_scripts', 'fbs')()
File "/home/jorge/.virtualenvs/QtOpencv/venv/lib/python3.6/site-packages/fbs/main.py", line 17, in _main
fbs.cmdline.main()
File "/home/jorge/.virtualenvs/QtOpencv/venv/lib/python3.6/site-packages/fbs/cmdline.py", line 32, in main
fn(*args)
File "/home/jorge/.virtualenvs/QtOpencv/venv/lib/python3.6/site-packages/fbs/builtin_commands/init.py", line 158, in installer
create_installer_ubuntu()
File "/home/jorge/.virtualenvs/QtOpencv/venv/lib/python3.6/site-packages/fbs/installer/ubuntu.py", line 4, in create_installer_ubuntu
generate_installer_files()
File "/home/jorge/.virtualenvs/QtOpencv/venv/lib/python3.6/site-packages/fbs/installer/linux.py", line 21, in generate_installer_files
_generate_icons()
File "/home/jorge/.virtualenvs/QtOpencv/venv/lib/python3.6/site-packages/fbs/installer/linux.py", line 75, in _generate_icons
for size, _, icon_path in get_icons():
File "/home/jorge/.virtualenvs/QtOpencv/venv/lib/python3.6/site-packages/fbs/resources.py", line 48, in get_icons
raise FbsError('Invalid icon name: ' % icon_path)
TypeError: not all arguments converted during string formatting

Regards

**Comment by jerubio** [comment]
I uninstalled fbs and reinstalled it.
Everything works fine now.
